// ===================== CULTS LIBRARY DATA =====================
// Backing data for the Compendium's Cults sub-tab (see renderCultsCompendium in the main file).
// Split into its own file the same way loot-data.js/puzzle-data.js/trap-data.js are — pure
// content, no logic, loaded via a plain <script src> before the main file's own script runs.
//
// Original content written for this project (not transcribed from any published sourcebook) --
// covers the same functional ground as a published "cult" writeup (a patron, a goal, a structure,
// rites, secrets, adventure hooks) with each entry's own specific name, agenda, and flavor.
//
// One shape:
//   {
//     name: "Cult Name",
//     alignment: "e.g. Chaotic Evil" — a rough moral compass, not a strict mechanical rule,
//     patron: "who or what they serve — an entity, an idea, a force of nature",
//     goal: "their actual overarching agenda, stated plainly",
//     symbol: "their iconography — what a party would actually recognize at a glance",
//     structure: "how the cult organizes itself, from leadership down to rank-and-file",
//     membership: "who actually joins one of these, and why",
//     practices: "rites, initiation, day-to-day observance",
//     secret: "the DM-facing hidden truth — what the cult doesn't tell its own members, or what
//              outsiders don't know",
//     hooks: "concrete ways a party might run into this cult and what's actually at stake",
//     notableFigure: { name, role, description } — one recurring NPC worth naming on sight,
//   }

const CULT_LIBRARY = [
  {
    name: "The Withering Choir",
    alignment: "Neutral Evil",
    patron: "An entity the cult calls the Unsung Rot — not a god in any conventional sense, but a hunger given voice, said to have first spoken through a plague pit centuries ago.",
    goal: "To spread a wasting blight across a region slowly enough that it's mistaken for natural famine and disease until it's far too entrenched to stop.",
    symbol: "A wilted flower with its stem tied in a knot, scratched into doorframes or worn as a small tin pin.",
    structure: "Cells of five to seven led by a 'Cantor' who alone communes with the Rot. Cantors never meet each other directly — messages pass through blighted crops, tainted wells, or diseased livestock left as signs.",
    membership: "The desperate and the grieving: farmers who lost a harvest, parents who lost a child to illness, anyone the Choir's recruiters can convince that suffering has meaning if it's offered up rather than endured alone.",
    practices: "Nightly 'withering hymns' sung over a dying plant or animal, believed to feed the Rot a fraction of its hunger and buy the singer's own family safety. Initiates plant a seed in blighted soil and tend it until it dies, taking a fragment of the dead plant as a keepsake.",
    secret: "The Rot is real and growing — it's a slow, sapient magical blight that genuinely does spread faster wherever the Choir 'sings' to it, meaning every cell is unknowingly making the plague worse in exchange for a false promise of control over it.",
    hooks: "A village blames a bad harvest on weather until the party notices identical tin pins on three separate households. A Cantor offers to 'spare' a besieged town if the party delivers a blighted seed to a rival settlement. A cured plague victim remembers singing in their sleep.",
    notableFigure: { name: "Cantor Ilsevet Marrow", role: "Regional coordinator", description: "A former herbalist who lost her whole family to a fever the physicians couldn't name, and has convinced herself the Choir's hymns are the only mercy left in the world." },
  },
  {
    name: "The Ashbond",
    alignment: "Lawful Evil",
    patron: "Zaharos, self-styled 'the Last Ember' — an efreeti-blooded warlord-philosopher who came to believe that fire was never a destination, only the first and most honest door into magic's deeper truths, and built a faith around walking through it.",
    goal: "Officially, to guide the faithful toward genuine mastery of magic's depths, using flame — the discipline the order was founded on — as the first and most accessible study. In practice, a hidden circle inside the order's own temples has begun testing exactly how far that 'mastery' can be pushed, using willing devotees as both proof and subject. The Ashbond still holds Karvossa's hearth-licensing rights, a legitimate and lucrative Imperial charter that quietly funds everything else the order does.",
    symbol: "A closed fist wreathed in a single stylized flame, branded onto Firewarden equipment and worn by full devotees as a small pin — inner-circle initiates wear a second, near-identical pin with the flame drawn slightly incomplete, a mark meant to be invisible to anyone not already looking for it.",
    structure: "A rigid hierarchy on paper — Zaharos at the top, regional Firewardens beneath him, licensed 'Kindlers' running ordinary hearths and forges under Ashbond license — that no longer reflects where the order's real power sits. A hidden inner circle, led in practice by Firewarden Cassia Emberlyn and a handful of senior clergy, operates almost entirely inside the outer structure's blind spots, using the order's legitimate temples, funds, and follower rolls as cover.",
    membership: "Smiths, chandlers, and hearth-keepers who value the order's licensing and protection, ordinary devotees drawn to a faith that promises real, attainable magical understanding, and — within the inner circle only — a small number of true believers convinced that what they've glimpsed in the Deepening rites justifies anything it costs.",
    practices: "Public devotion centers on the 'First Spark' rite, where an initiate lights a forge with flame carried personally from Zaharos's own hearth, alongside ordinary hearth-blessings. Privately, the inner circle conducts 'Deepening' ceremonies: a devotee who has proven their faith is offered the chance to be 'consumed and remade' in pursuit of a genuine magical revelation. None have been remade. All have been consumed.",
    secret: "Zaharos's original philosophy is entirely sincere, and he has no idea what's grown inside his own order — he still believes the Ashbond simply studies and licenses flame, and would be horrified to learn what 'Deepening' actually means. Cassia Emberlyn and her circle genuinely believe the rites work: that magic's depths demand a real cost, and that every consumed devotee has purchased the order a fragment of true understanding no scholar could reach any other way. They have never once produced anything resembling proof.",
    hooks: "A devotee's family reports them missing after a 'sacred pilgrimage' the temple insists never happened. A blacksmith who refuses an Ashbond hearth-license finds their forge mysteriously going cold. Zaharos, increasingly troubled by rumors he can't quite trace, quietly asks the party to investigate his own order — without telling them what they might find. A Rebel cell has obtained a Deepening ceremony's ritual notes and needs the party to determine whether they're a fabrication or something far worse.",
    notableFigure: { name: "Firewarden Cassia Emberlyn", role: "Public Firewarden, true leader of the inner circle", description: "Efficient, unfailingly polite, and genuinely convinced she's uncovering something real — she keeps meticulous records of every Deepening and has never once let herself conclude the results don't justify the cost. Reports, on paper, to Zaharos. In practice, he has no idea how far beneath him she's already gone." },
  },
  {
    name: "The Hollow Choir of Saints",
    alignment: "Chaotic Evil",
    patron: "A chorus of imprisoned, minor deific fragments the cult calls 'the Unsainted' — beings once worshipped and then wholly forgotten, left to rot in the space between belief and oblivion.",
    goal: "To restore the Unsainted to godhood by feeding them fresh worship, one convert's genuine devotion at a time, regardless of what that devotion costs the convert.",
    symbol: "A halo drawn as a broken, incomplete circle — always missing the same specific arc, no matter who draws it.",
    structure: "No fixed hierarchy at all; the Choir operates as a web of independent 'Confessors,' each personally chosen (or so they believe) by one specific Unsainted fragment that speaks only to them.",
    membership: "The lonely and the overlooked — people who've never been prayed to, thanked, or truly seen, and who find something intoxicating in being told a god has finally, personally noticed them.",
    practices: "Private, one-on-one 'confession' rites where a Confessor pours out their genuine devotion to their patron fragment in exchange for small, real miracles — a healed wound, a lucky break, a vivid dream. Each miracle costs the fragment a little more of its remaining self.",
    secret: "The miracles are real, but they're not gifts — they're the Unsainted fragments spending down the last of what little divine essence they have left, meaning every 'answered prayer' brings that fragment closer to true, final oblivion, not restoration. The Choir's entire theology is a slow-motion mercy killing its members don't understand they're performing.",
    hooks: "An NPC who's clearly been touched by real, small-scale magic insists it's divine favor and refuses to discuss where it came from. The party finds a genuinely miraculous cure with no explainable source. A dying Unsainted fragment, in its last moments, begs the party for something no one can give it.",
    notableFigure: { name: "The Confessor Without a Name", role: "The Choir's oldest surviving member", description: "Has taken so many confessions from so many desperate people that they've stopped using their own name entirely, answering only to whatever their current patron fragment calls them." },
  },
  {
    name: "The Undertow Assembly",
    alignment: "Chaotic Neutral",
    patron: "The drowned dead of a specific sea, river, or lake — not any one entity, but the aggregate memory and grievance of everyone that body of water has ever claimed.",
    goal: "To 'balance the ledger' by ensuring the water takes exactly as many lives as it's owed each year, believing that interference (rescues, dredging, flood walls) only delays a debt that compounds with interest.",
    symbol: "A length of waterlogged rope tied in a specific sailor's knot, left at shrines, docks, or drowning sites.",
    structure: "Loosely organized around 'Tideskeepers' — usually sailors, ferrymen, or fisherfolk who claim to hear the drowned dead's count of who's still owed. No central leader; Tideskeepers who disagree on the count simply operate independently, sometimes in open conflict.",
    membership: "People who've survived a drowning themselves, or who lost someone to the water and came away believing it meant something rather than being random tragedy.",
    practices: "An annual 'Reckoning' where a Tideskeeper publicly announces how many the water is still owed that year, followed by ritual offerings (usually coin, sometimes livestock, rarely and controversially something worse) meant to satisfy the debt without an actual drowning.",
    secret: "There genuinely is a malevolent, semi-sentient undertow current native to the body of water in question, and it genuinely does calm down for a season after a Reckoning's offerings — not because of any real 'debt,' but because it's a predictable, food-motivated hazard that the Assembly has accidentally learned to bait and pacify like a wild animal, and mistaken for divine bookkeeping.",
    hooks: "A rash of drownings stops abruptly the same week the party notices unusual offerings at the docks. A Tideskeeper wants to 'pay the debt' with a criminal's life instead of livestock this year, and needs the party to look the other way — or stop them. A skeptical local wants proof the Assembly's Reckoning does nothing, and it's about to test that theory personally.",
    notableFigure: { name: "Tideskeeper Bram Hollowell", role: "Senior Reckoner of the river Assembly", description: "Pulled his own drowned brother from the water as a boy and has spent forty years since convinced he simply didn't pay enough attention to the signs beforehand." },
  },
  {
    name: "The Gilded Larder",
    alignment: "Neutral Evil",
    patron: "No deity — the cult worships appetite itself, personified in their teachings as a nameless, ever-hungry ideal they simply call 'the Feast.'",
    goal: "To acquire, hoard, and consume — wealth, land, rare delicacies, magic, influence — on the theory that true transcendence comes from wanting nothing left ungotten.",
    symbol: "A place setting for one, laid with excessive, mismatched finery, carved or painted wherever the cult marks its territory.",
    structure: "A strict social ladder based entirely on demonstrated appetite: the wealthier, more indulgent, and more acquisitive a member becomes, the higher they sit at the cult's literal and figurative table.",
    membership: "The already-wealthy looking for a philosophy that flatters their excess, plus a smaller number of the ambitious poor who've bought into the idea that unrestrained wanting is a virtue rather than a vice.",
    practices: "Monthly 'Feasts' that are equal parts banquet and status display — members are expected to bring something no one else at the table has ever had, and failing to impress carries real social (and sometimes financial) consequences.",
    secret: "The cult's leadership has quietly discovered that a specific rare delicacy served at the highest-tier Feasts is grown using a minor, genuinely parasitic magical fungus that heightens pleasure and appetite in the eater while slowly making them dependent on the Larder to supply more of it — the whole upper tier of 'true believers' is, functionally, being farmed.",
    hooks: "A noble family's sudden, reckless spending traces back to Larder membership. A rare ingredient the party needs for a commission turns out to be a controlled Larder delicacy, and getting it means attending a Feast. A former high-ranking member, cut off from their supply, is going through something that looks less like grief and more like withdrawal.",
    notableFigure: { name: "Host Threnody Vale", role: "Keeper of the Long Table", description: "Charming, tireless, and genuinely delighted by other people's wanting — collects protégés the way others collect wine, and never seems to notice when one of them stops being fun to watch." },
  },
  {
    name: "The Queen's Legion",
    alignment: "Lawful Evil",
    patron: "No deity, and not truly the Crown either, whatever the name suggests — a doctrine of quiet, total institutional capture: that real power isn't held by whoever sits the throne, but by whoever controls the people who actually process its paperwork.",
    goal: "To embed loyal placemen — tax assessors, court clerks, guild registrars, and sitting judges — throughout every lever of civic administration in Ashcrown territory, until the throne's official rulings and the Legion's private interests become functionally impossible to tell apart. The Legion no longer needs to infiltrate the Empire's civil service; it simply is the civil service, in every office that matters.",
    symbol: "A single unblinking eye inside a closed door, worn as a small enamel pin indistinguishable at a glance from an ordinary civil-service badge — meant to represent watchfulness paired with the comfort of never having to decide anything difficult yourself.",
    structure: "Modeled deliberately on ordinary bureaucracy rather than a hidden cabal — Legion members hold real administrative posts and advance the order's agenda through paperwork, precedent, and quiet favor-trading rather than secrecy. Above even Grand Inquisitor Vane sits a small, unnamed circle of Karvossa's wealthiest merchant-lords and old nobility, whose interests every Legion ruling ultimately serves.",
    membership: "Exhausted idealists who tried to fix the world through normal means and burned out into believing control was kinder than chaos, calculating careerists who simply enjoy the leverage, and, increasingly, ordinary officials who were never ideologues at all — just people who took one convenient bribe too many to ever refuse the next one.",
    practices: "No rites — 'devotion' means one more favorable ruling, one more quietly buried tax assessment, one more contract clause that moves money upward without ever technically breaking a law.",
    secret: "Grand Inquisitor Vane built the Legion from a single trial town, seeding every judge, collector, and guild registrar with his own people until the town ran orderly, prosperous on paper, and empty of anyone ambitious enough to stay. He's replicated it at Imperial scale since, for the same cabal that keeps Empress Isolde herself managed — a fact he knows and has shared with exactly one other person, Auditor Voss Ferrand.",
    hooks: "A town's suspiciously favorable tax assessments turn out to trace back to a single Legion-embedded collector. A magistrate NPC the party has trusted for the whole campaign is revealed to be quietly ruling in a hidden patron's favor. The party is offered a genuinely reasonable-sounding legal arrangement that would solve their current problem instantly, with a catch buried in the fine print. A rebel spy inside the civil service needs the party to steal one specific ruling before it's filed — not because of what it does, but because of whose money is actually behind it.",
    notableFigure: { name: "Grand Inquisitor Darrow Vane", role: "Founder and architect", description: "Soft-spoken, endlessly patient, and utterly convinced he is the only person left willing to make the hard, kind choice on everyone else's behalf. Holds a real Imperial title, Keeper of Ashcrown Loyalty, that gives him legitimate sign-off on more binding law than most sitting nobles." },
  },
  {
    name: "The Star-Fallen Kindred",
    alignment: "Chaotic Neutral",
    patron: "A shard of some unknown celestial body that crashed generations ago and has sat, quietly humming with unfamiliar energy, in a shrine the Kindred built around the impact crater.",
    goal: "To 'awaken' the shard fully, believing it to be a sleeping messenger from beyond the world that will usher in an age of revelation once it's sufficiently venerated.",
    symbol: "A jagged, asymmetrical star — never the same twice, since each Kindred shrine sketches it slightly differently based on local retellings.",
    structure: "Loose and communal, closer to a devoted village cult than a hierarchy — an elected 'Warden of the Light' oversees shrine upkeep and interprets the shard's supposed moods, but decisions are made by open gathering.",
    membership: "Mostly the descendants of the original settlers who witnessed the impact, plus pilgrims and star-touched scholars drawn by (exaggerated) rumors of the shard's power.",
    practices: "Nightly vigils at the crater shrine, offerings of polished stones and written wishes, and a yearly 'Long Watch' where the whole community stays awake through the night the impact supposedly occurred, waiting for a sign.",
    secret: "The shard isn't a messenger or a sleeping intelligence — it's inert, ordinary meteoric material that happens to sit atop a natural, unrelated ley-line convergence, and every 'sign' the Kindred has ever recorded is real ambient magical phenomena from the ley-line, misattributed to the rock sitting on top of it.",
    hooks: "A Kindred pilgrim asks the party to escort them to the shrine before the next Long Watch. Something at the crater genuinely does react to a specific spell or ritual the party performs nearby, seemingly confirming the Kindred's beliefs for entirely unrelated reasons. A rival scholar wants to remove the 'shard' for study, and the ensuing excavation risks destabilizing the ley-line no one but the party understands is the real source of the phenomena.",
    notableFigure: { name: "Warden Ysolde Nightglass", role: "Current Warden of the Light", description: "Inherited the role from her mother and grandmother before her, and has quietly begun to suspect the shard doesn't actually do anything — a doubt she hasn't told a single other Kindred member." },
  },
  {
    name: "The Marrow Compact",
    alignment: "Neutral Evil",
    patron: "No single entity — the Compact venerates undeath itself as a state of being, treating it as evolution rather than corruption.",
    goal: "To secure, through any means, a slow and voluntary transition to undeath for its highest-ranking members, believing true wisdom and mastery can only accumulate across a lifespan measured in centuries rather than decades.",
    symbol: "A single bone ring, unadorned, worn on the smallest finger — a small enough marker that a member can go a lifetime unrecognized by outsiders.",
    structure: "Organized as an ordinary-looking scholars' society on the surface, with genuine academic credentials and a real library — its true inner circle is a much smaller, invitation-only tier that actually pursues transition rites.",
    membership: "Aging scholars, mages, and nobles terrified of losing their accumulated knowledge and influence to something as mundane as old age.",
    practices: "Public-facing: ordinary academic study, lectures, and preservation of ancient texts. Privately, the inner circle conducts a years-long, deliberately slow 'Withering Rite' meant to transition a willing member into a lucid, controlled undead state without the usual loss of self.",
    secret: "The Withering Rite has never actually worked as intended — every member who's completed it has emerged with subtly, progressively eroded personality and judgment, becoming crueler and more erratic over subsequent years in ways the Compact's leadership either hasn't noticed or has decided not to acknowledge, because they're all still waiting for their own turn.",
    hooks: "A renowned scholar who died of natural causes 'according to the records' is spotted, changed, years later. The party is offered genuine, rare academic resources by the Compact's public society in exchange for retrieving something from a dangerous ruin — no strings attached, they insist. A completed Withering Rite subject begins acting erratically enough that even the Compact wants it quietly handled.",
    notableFigure: { name: "Archivist Corwin Dusklight", role: "Public face of the Compact's scholarly society", description: "Warm, brilliant, and only 'ninety-some years old, and looking better every decade' according to himself — genuinely doesn't realize how much of his old warmth has already worn away." },
  },
  {
    name: "The Bellwether Herd",
    alignment: "Chaotic Neutral",
    patron: "A primal, half-remembered nature spirit the cult calls the First Herd Mother, believed to have taught the first shepherds how to lead animals by earning trust rather than force.",
    goal: "To reclaim overdeveloped or overhunted wildland by any means necessary, including deliberately guiding dangerous beasts toward settlements that have encroached too far.",
    symbol: "A shepherd's crook wound with a length of animal fur, hung outside dens, groves, or migration paths the Herd considers protected.",
    structure: "Organized around 'Callers' — individuals with a genuine, sometimes magical rapport with local wildlife — who operate independently in their own territories but recognize a loose seniority based on how much land they successfully protect.",
    membership: "Rangers, druids, hunters-turned-conservationists, and a fair number of ordinary rural folk who've simply watched too much wild land vanish in their lifetime.",
    practices: "Seasonal 'Herding' rites where Callers physically walk the boundaries of protected land, renewing wards and reinforcing their bond with the animals who live there. Newer members prove themselves by successfully guiding a dangerous animal away from conflict without killing it.",
    secret: "A faction within the Herd has started deliberately breeding and releasing more aggressive predator populations near contested borderlands, reasoning that a wildland settlements are afraid to enter protects itself far more effectively than one they merely respect — a policy the founding Callers would never have sanctioned and don't yet know is happening.",
    hooks: "A logging camp suffers a string of unnaturally coordinated predator attacks. A Caller asks the party to help relocate a dangerous beast rather than kill it, over a settlement's objections. The party discovers evidence that a recent 'wild animal problem' was engineered, and has to decide whether the Herd's cause justifies its newer members' methods.",
    notableFigure: { name: "Caller Rook Amsel", role: "Senior boundary-walker", description: "Has a rapport with animals that borders on the supernatural and increasingly finds people, even fellow Herd members, harder to read and trust than the wolves he walks with." },
  },
  {
    name: "The Black Books",
    alignment: "Lawful Evil",
    patron: "No deity — the cult venerates obligation itself, treating every unpaid debt (financial, moral, or blood) as a binding cosmic force that must eventually be settled.",
    goal: "To accumulate leverage over as many powerful people as possible by manufacturing situations where they incur a debt to the Black Books, then calling those debts in at the moment of maximum advantage. Its most valuable holdings these days aren't merchants or disgraced nobles — they're sitting members of the Ashcrown court, several of whom owe the order favors large enough to end their careers, or their lives, if called in publicly.",
    symbol: "A single tally mark inside a circle, chalked discreetly wherever a debt has been recorded — a doorframe, a ledger book's flyleaf, the underside of a table. Inside the Imperial palace, it's sometimes scratched into the underside of a chair at a council table, where whoever's about to sit down has no idea it's there.",
    structure: "A strict creditor hierarchy: 'Notaries' record and manage debts in a given city, answering to regional 'Auditors' who decide when and how a debt gets called in, all ultimately reporting to an unseen 'First Creditor' almost no member has actually met.",
    membership: "Failed merchants, disgraced nobles, and calculating opportunists who've decided that being owed is safer than being liked.",
    practices: "No rites — the order's only sacrament is scrupulous, almost religious record-keeping. New Notaries are inducted by successfully engineering their first manufactured debt against an unwitting target.",
    secret: "The 'First Creditor' isn't a person at all — it's a magically animated, sentient ledger book that has been quietly rewriting its own rules for centuries to maximize the debts owed to it, and every Auditor who's ever tried to consult it in person has come away with subtly altered memories of what they agreed to. For nearly a decade, a small cabal of Karvossa's wealthiest merchant-lords and old nobility has been directing the Book's most sensitive collections toward one specific, patient project: manufacturing and calling in debts against the palace itself, one quiet favor at a time, until the Empress's own inner circle owed the Black Books more than they could ever openly repay. Whether the Book itself understands what it's being used for, or simply keeps accepting new debts the way it always has, is a question none of its Auditors have ever been foolish enough to ask aloud.",
    hooks: "An NPC ally suddenly, inexplicably owes the party's patron a debt neither of them remembers agreeing to. A Notary offers to erase a crushing debt in exchange for one small, seemingly harmless favor. The party gains access to the Black Books' actual ledger and has the chance to read — or alter — what it says they owe. A rebel leader wants the party to steal proof of exactly which imperial officials the Black Books own, reasoning that men who serve a debt collector before their Empress can be turned, or exposed — and suspects, without proof, that the list reaches further than anyone at the Second Flame has dared guess.",
    notableFigure: { name: "Auditor Voss Ferrand", role: "Regional debt-caller, Karvossa", description: "Meticulous, unfailingly courteous, and has never once raised his voice while ruining someone's life — genuinely believes he's just enforcing fair terms everyone agreed to. Holds no official position at court, and is nonetheless shown into rooms most petitioners wait months for." },
  },
];
