// ===================== NPC LIBRARY DATA =====================
// Backing data for the NPCs tab (see renderNpcsTab in the main file). Split into its own file
// the same way loot-data.js/cult-data.js/trap-data.js are — pure content, no logic, loaded via a
// plain <script src> before the main file's own script runs.
//
// Original content written for this project. Set in the Ashcrown Empire — a tyrannical state
// ruled from the capital, Karvossa, by House Draventh — and its opposition, a rebellion called
// the Second Flame. Three factions: Empire (the court and its instruments), Neutral (ordinary
// people in Ashcrown territory who aren't aligned with either side), and Rebel (the Second
// Flame and its allies). Several entries tie directly into CULT_LIBRARY (see cult-data.js) —
// the Ashbond, the Queen's Legion, and the Black Books all now operate partly or wholly
// through the Ashcrown court -- and, beneath all three, a quiet cabal of Karvossa's wealthiest
// merchant-lords and old nobility, who use the Black Books' leverage and a pair of trusted
// hands at court to keep the throne itself more manageable than anyone outside the palace
// realizes. See empress-isolde's own secrets field for the specifics.
//
// One shape:
//   {
//     id: "unique-slug",
//     name, title, faction: "Empire"|"Neutral"|"Rebel", role,
//     alignment, ac, hp (in the same "N (XdY+Z)" format monster records use), speed,
//     attacks: [{ name, text }],
//     weapon: "name of a signature weapon — see NPC_WEAPONS below, or freeform if not in it",
//     appearance: "race/ancestry, height, build, and the physical details a player would
//                  actually notice on sight — read-aloud-friendly, not DM-only",
//     traits: ["3-5 short phrases, not sentences -- how this NPC actually behaves in a scene:
//              speech habits, tics, what they do under pressure, how they treat strangers.
//              A quick-scan cue sheet for running them at the table, not a personality essay."],
//     backstory: "who they are and how they got here",
//     secrets: "DM-facing hidden information — not something the NPC volunteers",
//     cultTie: "a CULT_LIBRARY entry name this NPC is connected to, or null",
//     location: "where a party would actually find them",
//   }
// "The Patron" (the-patron) deliberately has no appearance field at all -- per their own
// backstory, nobody in the rebellion has ever met them in person, so there's nothing to
// describe. That absence is itself the point; don't fill it in.
// DM edits to any of these fields are stored separately (see npcEdits in the main file) and
// overlaid at render time, so this file itself never needs to be hand-edited to reflect a
// live campaign's changes.

const NPC_WEAPONS = [
  { name: "Cinderfall", desc: "The Lord Commander's greatsword, forged from meteoric iron and quenched in dragon's blood during the Ashcrown's conquest of the Cinder Coast. The blade never quite cools — Bastian Reave can light a torch off the edge in cold weather, and has, more than once, just to unsettle whoever he's meeting with.", type: "weapon", slotSize: 2, gp: "—", dmg: "2d6+5", effect: "+2 attack and damage. Once per turn on a hit, deal an extra 2d6 fire damage. Requires attunement by a creature of Lawful alignment." },
  { name: "The Vayle Codex", desc: "Not a book — a wand disguised as one, its spine bound in what the Archmagus insists is ordinary leather. Selwyn Vayle has carried it since his apprenticeship, and it's absorbed enough of his own spellwork over the decades that it now argues back, in a small dry voice only he claims to hear.", type: "weapon", slotSize: 1, gp: "—", dmg: "1d4", effect: "+3 to spell attack rolls and spell save DC while wielded. Once per long rest, cast Counterspell without using a spell slot or reaction — it happens automatically, faster than thought, whether or not its owner wanted it to.",
    abilities: [{ id: "vaylecodex-counterspell", name: "Counterspell", kind: "spell", icon: { school: "abjuration" }, spellName: "Counterspell", effectText: "Cast Counterspell without using a spell slot or reaction.", uses: { max: 1, recharge: "longRest" }, usesLeft: 1 }] },
  { name: "Korrin's Reckoning", desc: "General Thessaly Korrin's warhammer, cast from the melted-down chains of a rebellion she put down twenty years ago in the Cinder Coast — a trophy she commissioned herself, and wears without a trace of irony.", type: "weapon", slotSize: 2, gp: "—", dmg: "2d6+4", effect: "+2 attack and damage. On a critical hit, the target is Stunned until the end of its next turn." },
  { name: "Ashwick's Needle", desc: "A slim, unremarkable dagger the Imperial spymaster carries openly, on the theory that a weapon nobody bothers hiding is never suspected of anything.", type: "weapon", slotSize: 1, gp: "—", dmg: "1d4", effect: "Finesse, light, thrown (range 20/60). +1d6 poison damage on a hit against a creature that hasn't acted yet this combat." },
  { name: "The Legion Seal", desc: "Not a weapon by trade — a magistrate's signet ring, heavy gold, that Darrow Vane has worn since he folded the old civil register into the Queen's Legion. Every ruling he's ever quietly redirected carries its impression.", type: "misc", subcategory: "ring", slotSize: 1, gp: "—", effect: "While worn: once per long rest, force one creature within 30 ft. to make a DC 16 Wisdom save or be compelled to answer your next direct question honestly. Requires attunement.",
    abilities: [{ id: "legionseal-compel", name: "Compel Truth", kind: "debuff", icon: { kind: "debuff" }, effectText: "Force one creature within 30 ft. to make a DC 16 Wisdom save or be compelled to answer your next question honestly.", uses: { max: 1, recharge: "longRest" }, usesLeft: 1 }] },
  { name: "Vane's Judgment", desc: "The Grand Inquisitor's mace, blessed by a rite the Ashcrown temple no longer performs openly — it was meant, once, to be used against genuine heresy. Darrow Vane has widened the definition considerably.", type: "weapon", slotSize: 1, gp: "—", dmg: "1d6+4", effect: "+2 attack and damage. +2d6 radiant damage against a creature that has lied to you in the last minute." },
  { name: "Thorne's Answer", desc: "Commander Elara Thorne's longsword — Imperial-forged, taken off a Lord Commander's second-in-command the night she deserted. She's never had it reforged or rehilted. She wants every rebel who sees it to know exactly where it came from.", type: "weapon", slotSize: 1, gp: "—", dmg: "1d8+4", effect: "+2 attack and damage. Once per short rest, when you hit a creature wearing Ashcrown colors, gain advantage on your next attack roll against a different Ashcrown target within 1 minute." },
  { name: "The Cinderwright's Press", desc: "A collapsible printing frame small enough to fit in a courier's pack, used to run off pamphlets by moonlight and vanish before dawn. Not a weapon in any conventional sense — the Second Flame considers it one of their most dangerous assets anyway.", type: "misc", subcategory: "commonMisc", slotSize: 1, gp: "—", effect: "A single sheet run from this press, distributed and read aloud in a town within Ashcrown territory, grants the reader advantage on the next Charisma (Persuasion) check made to recruit help from the local population, once per settlement per month.",
    abilities: [{ id: "cinderwrightpress-pamphlet", name: "Print Pamphlet", kind: "buff", icon: { kind: "buff" }, effectText: "Advantage on your next Persuasion check to recruit local help, once per settlement per month.", uses: { max: 1, recharge: "longRest" }, usesLeft: 1 }] },
];

const NPC_LIBRARY = [
  // ══════════════════════ EMPIRE ══════════════════════
  {
    id: "empress-isolde",
    name: "Empress Isolde Draventh III", title: "Ruler of the Ashcrown Empire", faction: "Empire", role: "Royalty",
    alignment: "Lawful Evil", ac: 17, hp: "165 (22d8 + 66)", speed: "30 ft.",
    attacks: [
      { name: "Ceremonial Rapier", text: "Melee Weapon Attack: +9 to hit, reach 5 ft. Hit: 9 (1d8+5) piercing damage." },
      { name: "Word of the Throne (Recharge 6)", text: "Isolde speaks a single binding command. One creature she can see within 60 ft. must succeed on a DC 17 Wisdom save or be Charmed by her for 1 hour, treating her word as unquestionable law for that duration." },
    ],
    weapon: "A plain ceremonial rapier — she has never needed a better one",
    appearance: "Human, mid-forties, with the kind of composed bearing that reads as effortless until you notice how carefully maintained it is. Tall for a woman of the court, silver already threading through dark hair she refuses to let anyone dye for her. Her eyes are her most striking feature — a pale, unusual grey — and lately carry a faint, unfocused quality in unguarded moments that her attendants have learned not to remark on.",
    traits: ["Speaks slowly, like choosing words from very far away", "Defers to advisors more than a ruler should", "Brief, startled moments of sharp clarity"],
    backstory: "Isolde inherited a throne her father had already spent thirty years hollowing out, and she was, by most honest accounts, a genuine reformer for the first several years of her reign. Somewhere in the second decade — historians in her own court disagree on exactly when — the reforms stopped and the control measures didn't. She would tell you, if you asked her directly and she trusted you enough to answer honestly, that she is still governing exactly the way she always meant to. Nobody currently living has heard her answer that question honestly.",
    secrets: "Isolde's mind has been worn down for nearly a decade by Grand Inquisitor Darrow Vane's private 'loyalty devotions,' using tinctures sourced through Auditor Voss Ferrand — both men acting for a cabal of Karvossa's wealthiest merchant-lords and old nobility who profit more from a pliable Empress than a reforming one. She still knows what the Queen's Legion does through her own civil service, and still approves it. She does not know her own son funds the rebellion against her.",
    cultTie: null,
    location: "The Sable Throne Room, Karvossa Palace — rarely leaves it in person.",
  },
  {
    id: "lord-commander-reave",
    name: "Lord Commander Bastian Reave", title: "Head of the Ashcrown Military", faction: "Empire", role: "Military Command",
    alignment: "Lawful Evil", ac: 18, hp: "152 (16d10 + 64)", speed: "30 ft.",
    attacks: [
      { name: "Cinderfall (Greatsword)", text: "Melee Weapon Attack: +10 to hit, reach 5 ft. Hit: 14 (2d6+7) slashing damage plus 7 (2d6) fire damage." },
      { name: "Rally the Line (1/Day)", text: "Bastian shouts a single order. Up to 6 allied creatures within 60 ft. that can hear him gain 15 temporary hit points and advantage on their next attack roll." },
    ],
    weapon: "Cinderfall",
    appearance: "Human, easily the largest person in most rooms he enters, built like the frontline soldier he still occasionally insists on being. A jagged scar runs from his left ear to his jaw, souvenir of a border skirmish he doesn't discuss. His hands are perpetually careful around small or fragile things, an odd tenderness that doesn't match the rest of him.",
    traits: ["Answers questions directly, even ones he shouldn't", "Visibly uncomfortable giving cruel orders", "Protective of anyone weaker in the room"],
    backstory: "Reave came up through the ranks the honest way, which is rarer in the Ashcrown military than the Empire likes to admit — but the loyalty everyone assumes comes from conviction actually comes from his younger sister, Sela, whose chronic illness has been kept survivable for years only through Imperial physicians and patronage that stop the moment Reave stops being useful to the Crown. He doesn't especially like the Empress, the court, or most of the nobles he's sworn to defend, and hasn't for a long time. He tells himself, and almost believes, that staying is the only way to keep Sela breathing — which is true enough that he's never quite found the nerve to test whether it's the whole truth.",
    secrets: "Reave keeps a private journal of orders he considers dishonorable — proof, if it's ever needed, that he never believed in any of it. His former subordinate, Second Flame defector Garrick Sable, still writes to a contact inside Reave's own command. Reave has never traced the letters, but suspects someone is writing them.",
    cultTie: null,
    location: "The Ashcrown war college, Karvossa, when not in the field.",
  },
  {
    id: "archmagus-vayle",
    name: "Archmagus Selwyn Vayle", title: "Court Mage of the Ashcrown Empire", faction: "Empire", role: "Court Mage",
    alignment: "Neutral Evil", ac: 15, hp: "110 (20d8 + 20)", speed: "30 ft.",
    attacks: [
      { name: "Force Bolt", text: "Ranged Spell Attack: +8 to hit, range 120 ft. Hit: 18 (4d6+4) force damage." },
      { name: "Counterspell (Recharges via the Vayle Codex)", text: "As a reaction, Selwyn can attempt to counter a spell being cast within 60 ft., automatically succeeding against a spell of 3rd level or lower." },
    ],
    weapon: "The Vayle Codex",
    appearance: "Human, thin to the point of gauntness, with ink-stained fingers and the stooped posture of someone who's spent thirty years reading by candlelight. Prematurely grey, though he's not yet fifty. Wears spectacles he doesn't strictly need anymore, out of habit more than necessity.",
    traits: ["Lectures without meaning to", "Avoids eye contact when lying", "Warms up instantly to real questions about magic"],
    backstory: "Selwyn was the most talented student his academy had produced in two generations, and he knew it at the time, which made the Empire's offer — funding, a title, a genuinely unlimited research budget — almost impossible to say no to. He tells himself, most days, that the research has been worth whatever it's cost. He has stopped, in the last few years, being entirely sure who he's telling that to.",
    secrets: "Selwyn has spent a decade quietly researching a way to sever his own binding oath to the Crown, closer to succeeding than he'd admit at court. He's also the unwitting conduit for Ophir Lund's intelligence to the Empire — Ophir's letters read as sentiment, but Selwyn has started passing along details about Rhoswen Ash's company that he shouldn't.",
    cultTie: null,
    location: "The Vayle Spire, an Imperial research tower on the palace grounds.",
  },
  {
    id: "general-korrin",
    name: "General Thessaly Korrin", title: "\"The Ashcrown's Hammer\"", faction: "Empire", role: "Field General",
    alignment: "Lawful Evil", ac: 17, hp: "138 (15d10 + 45)", speed: "30 ft.",
    attacks: [
      { name: "Korrin's Reckoning (Warhammer)", text: "Melee Weapon Attack: +9 to hit, reach 5 ft. Hit: 13 (2d6+6) bludgeoning damage." },
      { name: "Merciless Advance", text: "Once per turn, if Thessaly moves at least 10 ft. straight toward a creature before attacking it, that attack deals an extra 7 (2d6) damage." },
    ],
    weapon: "Korrin's Reckoning",
    appearance: "Human, broad-shouldered and weathered, with the permanent squint of someone who's spent decades in open-field campaigns. Close-cropped grey hair, a nose broken at least twice and never quite reset straight. Moves with the unhurried confidence of someone who has never once needed to prove she belongs in a room.",
    traits: ["Blunt to the point of rudeness", "Respects competence over rank", "Physically restless when forced to sit still"],
    backstory: "Thessaly put down the Cinder Coast rebellion two decades ago with a thoroughness that's still taught, admiringly, at the Ashcrown war college — and still spoken of in the Cinder Coast itself in a very different tone. She doesn't regret it, or says she doesn't, and has spent twenty years since trying to outrun the specific quiet that follows her into rooms where people know what she did there. Her fierce, uncomplicated loyalty to the Crown has made her enormously useful to more than just the Crown itself — a standing arrangement with a handful of Karvossa's wealthiest families keeps her supplied with land, coin, and favors well beyond her official commission, in exchange for making certain the Empire's fist stays exactly as heavy as they need it to be.",
    secrets: "Thessaly knows Second Flame field commander Rhoswen Ash is the grown daughter of a Cinder Coast family she personally condemned. She's told no one at court. Her income beyond official pay comes from the same cabal that keeps the throne managed — she's seen Auditor Ferrand's signature on enough transfers to be certain, even unconfirmed.",
    cultTie: null,
    location: "Wherever the Empire's newest front is — currently the Ashcrown's northern border.",
  },
  {
    id: "spymaster-ashwick",
    name: "Renn Ashwick", title: "Spymaster of the Ashcrown Empire", faction: "Empire", role: "Intelligence",
    alignment: "True Neutral", ac: 16, hp: "82 (15d8 + 15)", speed: "35 ft.",
    attacks: [
      { name: "Ashwick's Needle (Dagger)", text: "Melee or Ranged Weapon Attack: +8 to hit, reach 5 ft. or range 20/60 ft. Hit: 6 (1d4+4) piercing damage plus 7 (2d6) poison damage if the target hasn't acted yet this combat." },
      { name: "Vanish (Recharge 5-6)", text: "Renn becomes invisible until the end of their next turn or until they attack." },
    ],
    weapon: "Ashwick's Needle",
    appearance: "Human, or at least appears to be — average height, average build, forgettable features that seem to shift slightly in memory the moment they're out of sight. Renn has been described by a dozen different witnesses as a dozen subtly different people, which is either a remarkable coincidence or, more likely, entirely deliberate.",
    traits: ["Answers questions with questions", "Never confirms or denies anything directly", "Remembers small details about strangers, unnervingly well"],
    backstory: "Nobody at court, including the Empress, is entirely certain where Renn came from before they took the position — which is, Renn would point out, exactly the resume a spymaster ought to have. They serve the Crown efficiently, without any particular ideological commitment to it, and have made it clear through two decades of consistent behavior that their actual loyalty is to information itself: having it, controlling who else has it, and never being caught not having enough of it.",
    secrets: "Renn already knows Crown Prince Aldric is secretly funding the Second Flame, and hasn't reported it. They've also confirmed Ophir Lund is feeding the Empire real intelligence through Archmagus Vayle — information Renn is sitting on for the same unstated reason.",
    cultTie: null,
    location: "Officially, an unremarkable townhouse in Karvossa's administrative district. Unofficially, wherever the current problem is.",
  },
  {
    id: "firewarden-emberlyn",
    name: "Firewarden Cassia Emberlyn", title: "Firewarden, The Ashbond", faction: "Empire", role: "Enforcer / Administrator",
    alignment: "Lawful Evil", ac: 15, hp: "97 (13d8 + 39)", speed: "30 ft.",
    attacks: [
      { name: "Fire-Brand Cudgel", text: "Melee Weapon Attack: +7 to hit, reach 5 ft. Hit: 9 (1d8+4) bludgeoning damage plus 7 (2d6) fire damage." },
      { name: "Hearth-Seal (1/Day)", text: "Cassia can extinguish or ignite any mundane fire within 30 ft. as an action — used most often to make her point about whose forges stay lit." },
    ],
    weapon: "A fire-brand cudgel, standard Concord issue",
    appearance: "Human, trim and precise in bearing, with the permanently soot-shadowed hands of someone who genuinely still works a hearth-inspection circuit rather than delegating it. Keeps her dark hair cropped short and practical. Her eyes have a settled, unblinking calm that some find reassuring and others find faintly unnerving without being able to say why.",
    traits: ["Warm and approachable, disarmingly so", "Takes careful notes on everything", "Genuinely believes she's helping"],
    backstory: "Publicly, Cassia is a mid-ranking Firewarden overseeing Karvossa's hearth registry — competent, well-liked, unremarkable. In truth, she is the one who transformed the Ashbond from Zaharos's earnest, half-forgotten fire-philosophy into something with real teeth: a working circle, hidden inside the order's own temples, that has spent years quietly identifying its most devoted followers and offering them the 'honor' of a deeper rite. She genuinely believes, and this is what makes her frightening rather than simply cruel, that what she's uncovered in those rites is real — a glimpse of magic's actual depths, bought at a price she considers entirely fair, since every subject volunteers, in their own way, for a communion they're told is sacred. Zaharos has no idea what his order has become beneath him.",
    secrets: "Cassia coordinates with a small circle of the Ashbond's senior clergy to select and prepare 'volunteers' for what the inner circle calls Deepening ceremonies. She keeps meticulous records of every subject and every result — records Zaharos has never once asked to see.",
    cultTie: "The Ashbond",
    location: "The Karvossa hearth-registry office, most weekday mornings.",
  },
  {
    id: "auditor-ferrand",
    name: "Auditor Voss Ferrand", title: "Regional Debt-Caller, The Black Books", faction: "Empire", role: "Court Manipulator",
    alignment: "Lawful Evil", ac: 13, hp: "71 (13d8 + 13)", speed: "30 ft.",
    attacks: [
      { name: "Called Debt", text: "As an action, Voss can 'call in' a debt held over one creature within 30 ft. that owes the Ledger: DC 15 Charisma save or that creature is Frightened of Voss for 1 minute, its composure visibly cracking in front of anyone watching." },
    ],
    weapon: "None — Voss has never needed to raise a hand to anyone in his professional life",
    appearance: "Human, immaculately groomed, with manicured hands that have genuinely never done a day of physical labor. Medium height, unremarkable build, dressed always a half-step more expensively than his modest official rank would suggest. Smiles often. It rarely reaches his eyes.",
    traits: ["Never raises his voice", "Smiles constantly, means it rarely", "Remembers every favor owed to him, exactly"],
    backstory: "Voss holds no official Imperial title, and is shown into rooms most petitioners wait months to enter anyway, which tells you most of what you need to know about how the Ledger's business actually gets done. He is unfailingly courteous to everyone he ruins, and seems to genuinely believe this makes the ruining fair.",
    secrets: "Voss doesn't know the First Creditor is a sentient, self-editing book rather than a person. What he does know is that a cabal of Karvossa's wealthiest families directs the Black Books' most sensitive collections, and that his own tinctures and called-in debts have spent a decade keeping one very particular debtor compliant — supplied directly to Grand Inquisitor Vane, the only other person who knows where they actually go.",
    cultTie: "The Black Books",
    location: "A modest townhouse near the palace that somehow always has an appointment available.",
  },
  {
    id: "grand-inquisitor-vane",
    name: "Grand Inquisitor Darrow Vane", title: "Grand Inquisitor & Architect of the Queen's Legion", faction: "Empire", role: "Loyalty Enforcement",
    alignment: "Lawful Evil", ac: 16, hp: "104 (14d8 + 42)", speed: "30 ft.",
    attacks: [
      { name: "Vane's Judgment (Mace)", text: "Melee Weapon Attack: +8 to hit, reach 5 ft. Hit: 8 (1d6+5) bludgeoning damage plus 7 (2d6) radiant damage if the target has lied to Darrow in the last minute." },
      { name: "Detect Falsehood (At Will)", text: "Darrow can tell, with unsettling reliability, whether the last thing a creature said to him was a lie — though not what the truth actually is." },
      { name: "The Legion Seal", text: "As an action, Darrow can invoke a standing ordinance against one creature within 30 ft. who is a citizen of the Empire: DC 16 Wisdom save or the target is bound by a compulsory oath of his choosing for 24 hours (GM adjudicates specifics; typically a restriction on movement, speech, or action, not direct harm)." },
    ],
    weapon: "Vane's Judgment",
    appearance: "Human, tall and gaunt in the particular way of someone who treats fasting as a virtue, with close-cropped iron-grey hair and pale eyes that hold a gaze a beat longer than comfortable. A thin ritual scar marks his left palm, self-inflicted during his ordination decades ago. Wears a heavy gold signet ring on his right hand that has nothing to do with the temple.",
    traits: ["Holds eye contact a beat too long", "Speaks in measured, deliberate sentences", "Treats every conversation like a quiet interrogation"],
    backstory: "Darrow was ordained to root out genuine heresy, back when the Ashcrown temple still drew a real distinction between that and simple political inconvenience. He's spent two decades widening what counts as either. Trials alone couldn't reach far enough — a heretic could be burned, but a whole town of quietly disobedient citizens couldn't — so he built the Queen's Legion to close that gap: loyal judges, tax collectors, and guild registrars answering to him instead of a thousand competing consciences. He tested it first on a single small town, seeding his own people through its court and commerce until the town ran orderly, prosperous on paper, and slowly empty of anyone ambitious enough to want to stay. He has since replicated it at Imperial scale, for patrons who pay very well for exactly that kind of order, and would tell you, honestly, that he has never once punished an innocent person — a claim that's only true because of how thoroughly he's redefined the word.",
    secrets: "Darrow personally conducts Empress Isolde's private 'loyalty devotions' using tinctures Auditor Voss Ferrand supplies — the two have never once discussed what the rite actually does to her, and neither has stopped. He's one of only two people alive who know the Queen's Legion and the throne itself answer to the same hidden cabal; Ferrand is the other. His estranged sister, entertainer Lysette Vane, has been secretly watched by his own agents for years. She has no idea.",
    cultTie: "The Queen's Legion",
    location: "The Ashcrown temple's inquisitorial wing most mornings, the Hall of Ordinance most afternoons.",
  },
  {
    id: "prince-aldric",
    name: "Crown Prince Aldric Draventh", title: "Heir to the Ashcrown Throne", faction: "Empire", role: "Royalty",
    alignment: "Neutral Good", ac: 14, hp: "76 (12d8 + 24)", speed: "30 ft.",
    attacks: [
      { name: "Courtly Rapier", text: "Melee Weapon Attack: +6 to hit, reach 5 ft. Hit: 7 (1d8+3) piercing damage." },
    ],
    weapon: "An unremarkable court rapier — Aldric has never wanted to be good at this",
    appearance: "Human, mid-twenties, with his mother's pale grey eyes but none of her practiced composure — he fidgets, especially in formal settings, a habit two decades of etiquette tutors have never quite trained out of him. Slight of build, more suited to a rapier's finesse than any heavier weapon, which suits him fine.",
    traits: ["Fidgets in formal settings", "Overly polite to servants and guards", "Deflects personal questions with self-deprecating humor"],
    backstory: "Aldric has spent his entire adult life performing exactly the heir his mother expects, well enough that no one at court — including, most days, Aldric himself — questions it. He started diverting a small, carefully laundered portion of his personal allowance to a rebel contact almost four years ago, after a conversation he's never told anyone about, with someone he met exactly once, whose name he still doesn't know.",
    secrets: "Aldric is the Second Flame's anonymous benefactor, known within the rebellion only as 'the Patron.' Spymaster Ashwick already suspects; his mother does not. He believes he's fighting a tyrant who chose this. He has no idea he may actually be fighting to free her.",
    cultTie: null,
    location: "Karvossa Palace, performing his role, when he isn't somewhere he's not supposed to be.",
  },

  // ══════════════════════ NEUTRAL ══════════════════════
  {
    id: "innkeeper-thatch",
    name: "Mirna Thatch", title: "Proprietor, the Guttering Lantern", faction: "Neutral", role: "Innkeeper",
    alignment: "Lawful Neutral", ac: 11, hp: "27 (5d8 + 5)", speed: "25 ft.",
    attacks: [ { name: "Iron Skillet", text: "Melee Weapon Attack: +3 to hit, reach 5 ft. Hit: 4 (1d6+1) bludgeoning damage — and Mirna has genuinely knocked out a drunk noble's guard with this before." } ],
    weapon: "A well-used iron skillet, kept within reach at all times",
    appearance: "Human, stout and strong-armed from a decade of hauling kegs and cracking heads when necessary, with a perpetual flour-dust smudge somewhere on her apron no matter the hour. Grey-streaked brown hair, always tied back, and a stare that's ended more bar fights than her skillet ever has.",
    traits: ["No-nonsense, doesn't tolerate trouble", "Fiercely protective of her regulars", "Softens instantly around genuine kindness"],
    backstory: "Mirna has run the Guttering Lantern for eleven years and has made exactly one rule stick the entire time: whatever you are outside her door, inside it you're a paying customer and nothing else. Imperial officers, rebel couriers, and ordinary travelers have all shared her common room on the same night without incident, because Mirna has made it very clear what happens to anyone who starts trouble under her roof, regardless of whose colors they wear.",
    secrets: "Mirna lets Second Flame couriers use her cellar as a dead drop — not conviction, just that the first one who asked tipped well.",
    cultTie: null,
    location: "The Guttering Lantern, a mid-size inn in Karvossa's lower city.",
  },
  {
    id: "blacksmith-iresmith",
    name: "Toren Iresmith", title: "Independent Smith", faction: "Neutral", role: "Blacksmith",
    alignment: "True Neutral", ac: 13, hp: "44 (6d8 + 12)", speed: "30 ft.",
    attacks: [ { name: "Smithing Hammer", text: "Melee Weapon Attack: +5 to hit, reach 5 ft. Hit: 7 (1d8+3) bludgeoning damage." } ],
    weapon: "A smithing hammer, which Toren can use rather more precisely than his customers realize",
    appearance: "Dwarf, broad and dense with forge-hardened muscle, forearms scarred pale from old burns he's stopped bothering to hide. Keeps his beard short and practical rather than in the elaborate braids some of his kin favor, on the grounds that a beard on fire is nobody's idea of tradition worth keeping.",
    traits: ["Gruff but fair in trade", "Slow to trust, loyal once earned", "Mutters to himself while working"],
    backstory: "Toren refused an Ashbond hearth-tax license three separate times before finally paying up, and has been quietly overcharging Ashbond officials and undercharging everyone else ever since — a small, deniable act of protest he's fairly sure the Firewarden assigned to his district has noticed and chosen not to escalate.",
    secrets: "Toren still keeps his forge lit with unlicensed flint after Ashbond curfew, one night in three, and has never once been caught — mostly because Cassia Emberlyn's district reports have started developing convenient blind spots around his street.",
    cultTie: null,
    location: "Iresmith's Forge, on the edge of Karvossa's artisan quarter.",
  },
  {
    id: "broker-whisper",
    name: "\"Whisper\"", title: "Information Broker", faction: "Neutral", role: "Fence / Information Broker",
    alignment: "Chaotic Neutral", ac: 14, hp: "38 (7d8 + 7)", speed: "30 ft.",
    attacks: [ { name: "Concealed Dagger", text: "Melee Weapon Attack: +5 to hit, reach 5 ft. Hit: 5 (1d4+3) piercing damage." } ],
    weapon: "A dagger nobody's ever actually seen — that's rather the point",
    appearance: "Never quite the same twice — clients who've met 'Whisper' independently give contradictory descriptions: a tall man with a limp, a short woman with a sharp accent, once even a reedy adolescent voice from behind a market stall. Nobody has ever compared notes carefully enough to realize why the descriptions never match, which is rather the point.",
    traits: ["Never seen directly, only heard or read", "Transactional, never personal", "Prices information by how badly you want it"],
    backstory: "Nobody in Karvossa knows Whisper's real name or face, including, according to Whisper, most of Whisper's own regular clients. Information moves through a chain of go-betweens and dead drops precise enough that both Ashcrown intelligence and the Second Flame have separately tried to buy Whisper's loyalty outright — and both have separately concluded that Whisper simply doesn't have one to sell, which is exactly the reputation Whisper has spent a decade building.",
    secrets: "Whisper is, in fact, three different people operating under one shared identity and a strict rule against ever appearing together — a secret that would unravel the entire brand instantly if it got out.",
    cultTie: null,
    location: "Never the same place twice. Messages go through the Guttering Lantern's back room.",
  },
  {
    id: "mercenary-ostergaard",
    name: "Kade Ostergaard", title: "Captain, the Ashen Blades", faction: "Neutral", role: "Mercenary Captain",
    alignment: "Chaotic Neutral", ac: 16, hp: "93 (11d8 + 44)", speed: "30 ft.",
    attacks: [
      { name: "Longsword", text: "Melee Weapon Attack: +7 to hit, reach 5 ft. Hit: 10 (1d8+6) slashing damage." },
      { name: "Rally", text: "Once per short rest, Kade can grant up to 4 allies within 30 ft. 10 temporary hit points as a bonus action." },
    ],
    weapon: "A well-maintained longsword, nothing fancy, exactly as advertised",
    appearance: "Human, solidly built and battle-scarred in the unglamorous way of someone who's survived more skirmishes than he's won outright. Keeps a neatly trimmed beard and expensive, well-maintained armor — a walking advertisement for a company that takes its contracts seriously.",
    traits: ["Businesslike, weighs every interaction by cost and benefit", "Respects professionalism in others", "Doesn't make promises he won't keep"],
    backstory: "Kade's company takes contracts from the Empire, from merchant houses, and — carefully, through enough intermediaries to maintain deniability — occasionally from the Second Flame, on the theory that a mercenary who's picky about politics doesn't stay in business long in a country this unstable. Kade's actual loyalty is to the company's own survival and reputation, in that order, and has kept both intact for nine years through consistent, almost stubborn professionalism.",
    secrets: "Kade turned down a lucrative standing contract from Lord Commander Reave to garrison a rebel-sympathetic town — occupying civilians instead of fighting soldiers wasn't a line he'd cross, even unpaid.",
    cultTie: null,
    location: "Wherever the Ashen Blades' current contract is; based out of Karvossa between jobs.",
  },
  {
    id: "physician-correll",
    name: "Dr. Aveline Correll", title: "Physician", faction: "Neutral", role: "Healer",
    alignment: "Neutral Good", ac: 11, hp: "22 (4d8 + 4)", speed: "30 ft.",
    attacks: [ { name: "Surgical Knife", text: "Melee Weapon Attack: +2 to hit, reach 5 ft. Hit: 2 (1d4) piercing damage — Aveline has never once used this on a person and would rather it stayed that way." } ],
    weapon: "A surgical kit, used exclusively for its intended purpose",
    appearance: "Human, of middling height with the permanently rolled-up sleeves and short, practical nails of someone who can't afford delicate hands in her line of work. Tired eyes that soften noticeably around actual patients. Smells faintly of antiseptic herbs no matter how recently she's bathed.",
    traits: ["Brusque with time-wasters, gentle with patients", "Asks fewer questions than she could", "Exhausted but never careless"],
    backstory: "Aveline treats whoever walks through her door — Imperial soldiers, rebel couriers wounded badly enough to risk it, and everyone in between — and has made her clinic's neutrality a matter of fairly public principle, on the theory that a healer who picks sides eventually stops being trusted by anyone at all. It's cost her business from both directions more than once. She hasn't budged.",
    secrets: "Aveline has treated Crown Prince Aldric for a recurring wound she's certain came from a rebel skirmish. She's never asked him directly — confirming it would mean she'd have to report it.",
    cultTie: null,
    location: "Correll's Clinic, Karvossa's lower city, always open.",
  },
  {
    id: "guildmaster-coldwell",
    name: "\"Baron\" Ezra Coldwell", title: "Merchant Guildmaster", faction: "Neutral", role: "Merchant",
    alignment: "Lawful Neutral", ac: 10, hp: "18 (4d8)", speed: "25 ft.",
    attacks: [ { name: "Walking Cane", text: "Melee Weapon Attack: +1 to hit, reach 5 ft. Hit: 2 (1d4) bludgeoning damage — purely ornamental until it very much isn't." } ],
    weapon: "A cane with a concealed short blade, which Ezra has drawn exactly once in twenty years",
    appearance: "Human, portly and pink-cheeked in the well-fed way of a man who's never missed a meal in thirty years, dressed a full social class above his actual birth and entirely aware of it. Favors an elaborate mustache that's more grey than the rest of his hair combined, groomed with real, borderline excessive, daily attention.",
    traits: ["Performs more confidence than he feels", "Name-drops constantly", "Genuinely enjoys a good negotiation"],
    backstory: "Ezra isn't actually a baron — the title is decades-old self-promotion that stuck so well most of Karvossa has forgotten it isn't real, including, occasionally, Ezra himself. He runs the merchant guild with genuine competence and a strict rule against discussing politics on guild premises, which he enforces less because he's neutral and more because he's watched too many profitable trade relationships die over an argument about the Crown.",
    secrets: "Ezra has been quietly overcharging the Empire on military supply contracts for years, skimming a modest but steady percentage that no Imperial auditor has caught — mostly because Auditor Voss Ferrand has his own reasons for never looking too closely at Ezra's books.",
    cultTie: null,
    location: "The Merchant Guild hall, central Karvossa.",
  },
  {
    id: "hedge-mage-yura",
    name: "Old Yura", title: "Fortune Teller", faction: "Neutral", role: "Hedge Mage",
    alignment: "Chaotic Neutral", ac: 12, hp: "31 (7d8)", speed: "30 ft.",
    attacks: [ { name: "Minor Hex", text: "Ranged Spell Attack: +4 to hit, range 30 ft. Hit: 7 (2d6) necrotic damage." } ],
    weapon: "The Cinderwright's Press",
    appearance: "Human, small and stooped with age, wrapped in layers of mismatched, deliberately theatrical scarves and shawls that do a remarkably good job of making an otherwise unremarkable old woman impossible to look away from. Sharp, dark eyes that miss very little, in a face so thoroughly weathered it's genuinely hard to guess her age within a decade either way — which, she'd be the first to admit, works entirely in her favor.",
    traits: ["Theatrical, leans into the mystique", "Watches faces more than cards", "Deflects real questions with a joke"],
    backstory: "Yura has been telling fortunes in the same market square for longer than most of her regular customers have been alive, and the honest ones will admit her cold readings are unsettlingly good — not magic, she insists, just forty years of watching people's faces while they ask questions they already know the answer to. The dishonest ones insist it's definitely magic. Yura finds both reactions equally funny. What none of them know is that after the stall closes, the same hands that read palms all day set type by candlelight — Yura is the Cinderwright, the Second Flame's most effective propagandist, and the sharp, funny, deliberately quotable pamphlets bearing that name have turned more ordinary Karvossa citizens sympathetic to the rebellion than any battle the Second Flame has fought.",
    secrets: "Yura genuinely does have a minor, real gift for prophecy that she's spent decades underselling as showmanship — and it's the actual reason she's still free. Three times an Inquisitorial investigation has closed in on the Cinderwright's real identity, and three times a flash of warning has let her close the stall early or burn a draft just in time: a junior Inquisitor reassigned to a distant posting, a paid informant who watched her stall for a month and never suspected her, and a third investigator, active right now, closer than either of the first two. Grand Inquisitor Vane has personally ordered all three. Her pamphlets move through the city the same way Second Flame supplies do — through Whisper, who has never confirmed to Yura that the two of them are moving more than one kind of contraband.",
    cultTie: null,
    location: "The Karvossa market square, most days, weather permitting.",
  },
  {
    id: "smuggler-callaway",
    name: "Finn Callaway", title: "Dockhand", faction: "Neutral", role: "Smuggler",
    alignment: "Chaotic Neutral", ac: 13, hp: "33 (6d8 + 6)", speed: "30 ft.",
    attacks: [ { name: "Boat Hook", text: "Melee Weapon Attack: +4 to hit, reach 10 ft. Hit: 6 (1d6+3) piercing damage." } ],
    weapon: "A boat hook, and a genuinely excellent memory for which crates aren't supposed to be inspected",
    appearance: "Human, lean and quick-moving, with the permanent squint of someone who's spent most of his life on open water. Rope-callused hands and a gait that still rolls slightly even on dry land. Keeps his dark hair cropped close so nothing catches on rigging — old habit, kept out of comfort more than necessity.",
    traits: ["Quick with a joke to defuse tension", "Doesn't ask questions he doesn't want answered", "Nervous around anyone in uniform"],
    backstory: "Finn moves whatever pays, and has quietly decided that 'whatever pays' now excludes anything he's fairly sure is headed for an Ashcrown labor camp, a line he drew for himself after one specific job three years ago he still won't talk about. Everything else — contraband, tax-dodging merchant goods, the occasional favor for Whisper — is just business.",
    secrets: "Finn has moved Second Flame supplies through the docks a dozen times without meeting anyone from the rebellion directly — Whisper handles the arrangements.",
    cultTie: null,
    location: "The Karvossa waterfront, working the night shift more often than not.",
  },
  {
    id: "veteran-brake",
    name: "Sergeant Hollis Brake", title: "Retired Imperial Soldier", faction: "Neutral", role: "Veteran",
    alignment: "Lawful Neutral", ac: 15, hp: "58 (9d8 + 18)", speed: "25 ft.",
    attacks: [ { name: "Old Service Sword", text: "Melee Weapon Attack: +5 to hit, reach 5 ft. Hit: 7 (1d8+3) slashing damage." } ],
    weapon: "His old Ashcrown-issue service sword, kept clean out of habit rather than sentiment",
    appearance: "Human, broad-shouldered even in his later years, with a soldier's ramrod posture that a bad leg has never quite managed to fully undo. Close-cropped grey hair, a face weathered more by weather than age, and forearms still corded with real, working muscle from a training yard he refuses to let go soft.",
    traits: ["Gruff, direct, no patience for excuses", "Genuinely invested in his students", "Avoids talking about the Empire directly"],
    backstory: "Hollis served eighteen years, took an honorable discharge after a leg wound that still aches before rain, and has spent the years since running a small training yard for anyone willing to pay for real sword instruction — soldiers, guards, the occasional adventuring party passing through. He doesn't talk about the Empire much either way. He talks, if asked directly, about the men he served with who didn't come home, and lets people draw their own conclusions about how he feels about what they died for.",
    secrets: "Hollis quietly trains a handful of Second Flame recruits under the cover of ordinary lessons, charging them the same rate as everyone else and never once discussing politics with them during a session.",
    cultTie: null,
    location: "Brake's Yard, a training ground on the edge of Karvossa.",
  },
  {
    id: "entertainer-lysette",
    name: "Lysette Vane", title: "Traveling Entertainer", faction: "Neutral", role: "Bard",
    alignment: "Chaotic Good", ac: 12, hp: "27 (6d8)", speed: "30 ft.",
    attacks: [ { name: "Rapier", text: "Melee Weapon Attack: +4 to hit, reach 5 ft. Hit: 5 (1d8+1) piercing damage." } ],
    weapon: "A rapier she carries for show more than defense, and a lute she's rather more dangerous with",
    appearance: "Human, slight and quick, with her brother's same pale eyes set in a far more expressive face — she's never learned, or never bothered, to keep her feelings as carefully hidden as he does. A thin scar through one eyebrow, never explained, from what she calls 'an argument with a very rude tavern patron' and nothing more.",
    traits: ["Deflects with a joke or a new song", "Reads a room's mood instantly", "Goes quiet when her brother comes up"],
    backstory: "Lysette plays taverns across Karvossa and the surrounding towns, and has built a reputation for songs that sound entirely apolitical right up until a listener actually thinks about the lyrics afterward. She hasn't spoken to her brother in eleven years, since well before he became Grand Inquisitor, and has never once mentioned the relation to anyone — not from fear, she'd say, but because she genuinely doesn't know how to explain him to people who'd assume the worst either way.",
    secrets: "Lysette has suspected for years that her brother's 'loyalty devotions' with the Empress aren't what the temple claims, though she's never had proof. She's never told anyone, including Darrow.",
    cultTie: null,
    location: "Rotates between Karvossa's taverns — the Guttering Lantern most often.",
  },

  // ══════════════════════ REBEL ══════════════════════
  {
    id: "commander-thorne",
    name: "Commander Elara Thorne", title: "Leader, the Second Flame", faction: "Rebel", role: "Rebellion Leader",
    alignment: "Chaotic Good", ac: 16, hp: "119 (14d8 + 56)", speed: "30 ft.",
    attacks: [
      { name: "Thorne's Answer (Longsword)", text: "Melee Weapon Attack: +8 to hit, reach 5 ft. Hit: 9 (1d8+5) slashing damage; +2d6 more against a creature wearing Ashcrown colors within the last minute of her hitting one." },
      { name: "Unbreakable Line (1/Day)", text: "Elara and up to 5 allies within 30 ft. gain advantage on saving throws against being Frightened for 1 hour." },
    ],
    weapon: "Thorne's Answer",
    appearance: "Human, tall and rangy with the lean, hard-used build of someone who trains alongside her own soldiers rather than above them. A long-healed burn scar traces one forearm from a supply-cache explosion she's never fully explained. Keeps her dark hair short and out of her face, on principle.",
    traits: ["Leads from the front, expects the same of others", "Doesn't sugarcoat bad odds", "Fiercely loyal to anyone who's earned it"],
    backstory: "Elara deserted the Ashcrown army nine years ago, after an order she still describes only as 'the one I couldn't carry out,' and has spent every year since building the Second Flame from a handful of fellow deserters into a real, coordinated resistance. She leads from the front more often than her own officers would prefer, on the stated principle that she'll never send someone somewhere she wouldn't go herself.",
    secrets: "Elara has never learned the Patron's identity, but she's traced two of the funding drops back to a courier who also works for Spymaster Ashwick — meaning someone inside the palace either funds the rebellion or is hunting whoever does, and she can't yet tell which.",
    cultTie: null,
    location: "A shifting network of safehouses outside Karvossa — never the same one twice in a row.",
  },
  {
    id: "defector-sable",
    name: "Garrick Sable", title: "Former Imperial Officer", faction: "Rebel", role: "Defector / Trainer",
    alignment: "Neutral Good", ac: 16, hp: "85 (10d8 + 40)", speed: "30 ft.",
    attacks: [ { name: "Imperial-Issue Longsword", text: "Melee Weapon Attack: +6 to hit, reach 5 ft. Hit: 8 (1d8+4) slashing damage." } ],
    weapon: "His old Imperial-issue longsword, filed clean of its unit markings",
    appearance: "Human, solidly built in the unmistakable mold of career Imperial infantry, though the posture's softened slightly with years away from formal drilling. Keeps his Imperial-issue haircut out of habit rather than loyalty, and still stands a half-step too rigid whenever a superior officer — even a rebel one — walks into the room.",
    traits: ["Rigid posture, old habits die hard", "Trains recruits with real patience", "Uncomfortable being thanked"],
    backstory: "Garrick served twelve years under Lord Commander Reave and defected the week after Reave's forces put down a food riot in a starving border town with more force than Garrick could stomach reconciling with the 'honor' he'd signed up believing in. He trains new Second Flame recruits in real military discipline now, and is, privately, the closest thing the rebellion has to a mirror of what Reave might have been under different circumstances.",
    secrets: "Garrick still writes to a former comrade serving under Reave, using a dead-drop neither has acknowledged. Reave has never traced the letters, but Garrick suspects he's started to look.",
    cultTie: null,
    location: "The Second Flame's main training camp, location known only to the inner circle.",
  },
  {
    id: "saboteur-nyx",
    name: "\"Nyx\"", title: "Saboteur", faction: "Rebel", role: "Spymaster / Saboteur",
    alignment: "Chaotic Neutral", ac: 15, hp: "66 (12d8 + 12)", speed: "35 ft.",
    attacks: [ { name: "Throwing Knives", text: "Ranged Weapon Attack: +6 to hit, range 20/60 ft. Hit: 6 (1d4+4) piercing damage." } ],
    weapon: "A set of balanced throwing knives, each one accounted for at the end of every job",
    appearance: "Unknown, deliberately — even fellow Second Flame members who've worked alongside Nyx for years describe wildly different heights, builds, and faces, and none of them have ever compared notes closely enough to notice the pattern. Whoever, or whatever, Nyx actually looks like, it isn't whatever they showed you.",
    traits: ["Says little, watches everything", "Precise and unhurried in a crisis", "Vanishes from conversations as easily as rooms"],
    backstory: "Nobody in the Second Flame, including Commander Thorne, knows Nyx's real name or background — an arrangement Nyx insisted on from the first day, on the reasoning that a saboteur who can be identified is a saboteur who can be used against everyone else. The work speaks for itself: three Ashcrown supply convoys hit clean in the last year alone, no casualties on either side, which is either a point of professional pride or a deliberate restraint nobody's asked about directly.",
    secrets: "Nyx has twice let an Ashcrown patrol escape a sabotage run rather than risk civilian bystanders. Neither incident was reported to Commander Thorne.",
    cultTie: null,
    location: "Never fixed. Reports to Elara Thorne through Garrick Sable.",
  },
  {
    id: "field-commander-ash",
    name: "Captain Rhoswen Ash", title: "Field Commander, the Second Flame", faction: "Rebel", role: "Field Commander",
    alignment: "Chaotic Good", ac: 15, hp: "78 (12d8 + 24)", speed: "30 ft.",
    attacks: [ { name: "Cinder Coast Spear", text: "Melee Weapon Attack: +6 to hit, reach 10 ft. Hit: 8 (1d6+4) piercing damage plus 3 (1d6) fire damage." } ],
    weapon: "A spear passed down from her Cinder Coast grandmother, its head still faintly warm to the touch",
    appearance: "Human, lean and sun-browned from years leading raids in open country, with a spear-callused grip and a Cinder Coast complexion a shade darker than most of Karvossa's pale nobility. Carries her grandmother's old burn scars on one hand — inherited, she says, though she's never explained how a scar gets passed down.",
    traits: ["Intense, doesn't relax easily", "Protective of her company to a fault", "Goes cold and quiet at the mention of Korrin"],
    backstory: "Rhoswen grew up on stories of the Cinder Coast rebellion her family survived — barely — and joined the Second Flame the day she was old enough to hold a spear properly, driven less by abstract politics than a very specific, inherited grudge against the general who led that campaign. She doesn't know General Korrin has recently learned exactly whose granddaughter is fighting against her now.",
    secrets: "Rhoswen carries a partial list of Cinder Coast families executed during the old campaign — her own family's name is on it. Korrin doesn't know Rhoswen has seen the actual document.",
    cultTie: null,
    location: "Leads the Second Flame's northern raiding companies, near the Ashcrown's contested border.",
  },
  {
    id: "rebel-mage-lund",
    name: "Ophir Lund", title: "Rebel Battle-Mage", faction: "Rebel", role: "Mage",
    alignment: "Chaotic Good", ac: 13, hp: "52 (10d8 + 10)", speed: "30 ft.",
    attacks: [ { name: "Scorching Ray", text: "Ranged Spell Attack: +5 to hit, range 60 ft. Hit: 10 (3d6) fire damage." } ],
    weapon: "A traveling staff, unremarkable-looking on purpose",
    appearance: "Human, thin and stoop-shouldered in the way of someone who spent formative years hunched over spellbooks rather than training yards. Ink-stained fingertips, tired eyes behind a cracked, much-repaired pair of spectacles, and a habit of flinching very slightly at loud, sudden noises that he's never explained to anyone in the company.",
    traits: ["Flinches at sudden loud noises", "Argues that caution saves lives", "Uncomfortable with praise for his fighting"],
    backstory: "Ophir washed out of the Ashcrown's official mage academy years before Selwyn Vayle rose to Archmagus — not from lack of talent, but from a refusal to sign the Crown's standard binding oath. That refusal was never principled, whatever the rebellion assumes: Ophir watched two friends die in an academy 'training incident' that was really a hushed-up duel over politics, and walked away convinced that everything people call freedom — the right to choose, to disagree, to fight for a cause — is just a slower, more decorated way of getting each other killed. The Second Flame offered talent without demanding the oath first, and Ophir joined it not out of belief in the cause, but because a rebellion already in motion is easier to quietly starve than one that never started at all.",
    secrets: "Ophir has spent years passing real intelligence on Rhoswen Ash's company to the Empire, funneled through his old teacher Selwyn Vayle under cover of ordinary letters. Spymaster Ashwick has already connected the pattern. Ophir doesn't know that.",
    cultTie: null,
    location: "Attached to Rhoswen Ash's northern companies.",
  },
  {
    id: "quartermaster-wexley",
    name: "\"Big\" Tam Wexley", title: "Quartermaster", faction: "Rebel", role: "Smuggler / Supply",
    alignment: "Neutral Good", ac: 14, hp: "60 (8d8 + 24)", speed: "30 ft.",
    attacks: [ { name: "Loading Hook", text: "Melee Weapon Attack: +5 to hit, reach 5 ft. Hit: 8 (1d8+4) piercing damage." } ],
    weapon: "A cargo hook that's seen more honest work than fighting, though it's done plenty of both",
    appearance: "Human, enormous — the nickname isn't irony — with a barrel chest built for hauling cargo and a booming laugh that carries across an entire supply camp. Thick, calloused hands that move with surprising delicacy when sorting fragile goods. Keeps a battered ledger tucked in his coat at all times, more protective of it than of most weapons.",
    traits: ["Booming, friendly, impossible to miss", "Meticulous about his ledger", "Treats supplies like they're personal responsibilities"],
    backstory: "Tam ran an honest freight business for fifteen years before an Ashcrown tax seizure over an unpaid Concord hearth-fee put him out of business overnight, and he's spent the years since moving supplies for the Second Flame with the same meticulous logistics sense he used to run legitimate cargo. He's fed, armed, and equipped more of the rebellion's fighters than anyone realizes, and takes more pride in a well-stocked supply line than in any battle.",
    secrets: "Tam runs supply routes with Finn Callaway on the Karvossa docks, arranged through Whisper. Neither has ever said out loud who they're really moving goods for.",
    cultTie: null,
    location: "A network of rural supply caches Tam alone knows the full map of.",
  },
  {
    id: "recruit-ashby",
    name: "Wren Ashby", title: "New Recruit", faction: "Rebel", role: "Idealist",
    alignment: "Chaotic Good", ac: 12, hp: "18 (4d8)", speed: "30 ft.",
    attacks: [ { name: "Hand Axe", text: "Melee or Ranged Weapon Attack: +3 to hit, reach 5 ft. or range 20/60 ft. Hit: 4 (1d6+1) slashing damage." } ],
    weapon: "A hand axe she's still not entirely comfortable using on a person",
    appearance: "Human, seventeen and still visibly growing into her own frame, all sharp elbows and restless energy she hasn't yet learned to sit still with. Cropped her hair short herself, unevenly, the week she joined — a small, deliberate break from the girl her family back home still expects her to be.",
    traits: ["Restless energy, talks fast when nervous", "Eager to prove herself", "Still flinches at real violence"],
    backstory: "Wren joined the Second Flame six months ago, seventeen years old and furious about a cousin conscripted into an Ashcrown labor levy, and has spent every day since discovering how much slower and more complicated real resistance is than she'd imagined it would be. She hasn't lost the fury. She's started, quietly, developing the patience to go with it, which everyone around her privately considers the more dangerous combination.",
    secrets: "Wren doesn't know Garrick Sable has been vouching for her to Commander Thorne for more dangerous assignments.",
    cultTie: null,
    location: "Training under Garrick Sable at the main camp.",
  },
  {
    id: "veteran-old-marrow",
    name: "\"Old Marrow\"", title: "Second Flame Veteran", faction: "Rebel", role: "Veteran",
    alignment: "Chaotic Neutral", ac: 14, hp: "71 (11d8 + 22)", speed: "25 ft.",
    attacks: [ { name: "Notched Battleaxe", text: "Melee Weapon Attack: +6 to hit, reach 5 ft. Hit: 9 (1d8+5) slashing damage." } ],
    weapon: "A battleaxe with more notches in the haft than anyone's bothered counting",
    appearance: "Weathered to the point of ageless — old enough that three different generations of recruits swear they were already grizzled veterans when they joined, young enough that Imperial records from twenty years ago still match the face closely enough to be a problem. More scars than bare skin at this point, and a notched battleaxe that's outlasted at least two suits of armor.",
    traits: ["Speaks rarely, and every word counts", "Unbothered by danger most people fear", "Tells a different version of their past every time"],
    backstory: "Nobody currently in the Second Flame remembers Old Marrow's real name, including — genuinely, by this point — Old Marrow, who has told the story of losing it so many different ways over so many years that even they aren't sure anymore which version is true. They've fought in every major engagement the rebellion has had since its founding, trained half the veteran fighters currently serving under Rhoswen Ash, and show no particular sign of stopping.",
    secrets: "Old Marrow's real name is a matter of Imperial record — they're a Cinder Coast rebellion survivor believed executed twenty years ago, and General Korrin's old campaign paperwork still lists them as confirmed dead.",
    cultTie: null,
    location: "Wherever the fighting is worst — Old Marrow has never once stayed at a safehouse by choice.",
  },
  {
    id: "the-patron",
    name: "\"The Patron\"", title: "Anonymous Benefactor", faction: "Rebel", role: "Financier",
    alignment: "Neutral Good", ac: 10, hp: "—", speed: "—",
    attacks: [],
    weapon: "None — the Patron has never been present for anything the money funds",
    backstory: "The Second Flame has never met its most valuable funding source in person. Money arrives through untraceable intermediaries, always precisely enough to matter without ever being so much it draws attention, and always timed with an accuracy that suggests the Patron knows more about the rebellion's real needs than an outside sympathizer reasonably should.",
    secrets: "The Patron is Crown Prince Aldric Draventh. Only Spymaster Renn Ashwick has connected this, and hasn't reported it.",
    cultTie: null,
    location: "Unknown to the rebellion. See Crown Prince Aldric Draventh (Empire) for the DM's own reference.",
  },
];

// ===================== NPC COMBAT DEFS =====================
// Combat-ready stat blocks for 29 of the 30 NPC_LIBRARY entries ("The Patron" is deliberately
// excluded -- per their own entry, nobody has ever met them in person, so there's no body to
// put on a battle map). Same shape as HUMAN_NPC_DEFS (see the main file) -- name/alignment/cr/
// ac/hitDice/ability scores/skills/saves, plus `actions` where a `{weapon, dice, dmgType,
// ability}` entry gets its to-hit and damage computed from the listed ability score and CR by
// the same humanNpcAttack() formula every other homebrew NPC in this app already uses (never
// hand-typed independently of the stat block, so numbers can't quietly drift out of sync), and
// a plain `{name, text}` entry is used as-is for anything that isn't a simple weapon swing
// (Rally the Line, Word of the Throne, Counterspell, and the like).
//
// HP/CON were derived directly from the flavor hp string already shown on each NPC's card (see
// NPC_LIBRARY above) -- same hit dice, same total, just decomposed into hitDice+con here so the
// combat version and the card version always read the same "165 (22d8 + 66)" at a glance. AC is
// carried over unchanged (humanNpc() takes it as a flat value, not auto-derived from DEX+armor,
// same as HUMAN_NPC_DEFS already does). CR is a rough narrative-power placement, not a strict
// DMG-by-defenses calculation -- consistent with how HUMAN_NPC_DEFS itself already treats CR
// (a "Human Guard" at CR 1/8 already runs hotter on AC than the DMG's own CR 1/8 benchmark).
//
// The main file maps this through humanNpc() (see CUSTOM_HUMAN_NPCS) into NPC_LIBRARY_MONSTERS
// and merges it into monsterDatabase, so every name here is selectable from the Combat tab's
// normal monster picker like any other creature.
const NPC_COMBAT_DEFS = [
  // ── Empire ──
  { name: "Empress Isolde Draventh III", alignment: "LE", cr: "12", ac: 17, hitDice: [22, 8], str: 12, dex: 14, con: 16, int: 15, wis: 14, cha: 20,
    skills: "Persuasion +10, Insight +7", saves: "WIS +7, CHA +10",
    actions: [{ weapon: "Ceremonial Rapier", dice: "1d8", dmgType: "piercing", ability: "dex" },
      { name: "Word of the Throne (Recharge 6)", text: "Isolde speaks a single binding command. One creature she can see within 60 ft. must succeed on a DC 18 Wisdom save or be Charmed by her for 1 hour, treating her word as unquestionable law for that duration." }],
    desc: "Ruler of the Ashcrown Empire. Rarely fights in person, and rarely needs to." },
  { name: "Lord Commander Bastian Reave", alignment: "LE", cr: "11", ac: 18, hitDice: [16, 10], str: 20, dex: 12, con: 18, int: 11, wis: 13, cha: 14,
    skills: "Athletics +9, Intimidation +6", saves: "STR +9, CON +8",
    actions: [{ name: "Multiattack", text: "Bastian makes two attacks with Cinderfall." },
      { weapon: "Cinderfall", dice: "2d6", dmgType: "slashing", ability: "str", extra: "Deals an extra 7 (2d6) fire damage." },
      { name: "Rally the Line (1/Day)", text: "Bastian shouts a single order. Up to 6 allied creatures within 60 ft. that can hear him gain 15 temporary hit points and advantage on their next attack roll." }],
    desc: "Head of the Ashcrown military. Leads from the front more often than his rank requires." },
  { name: "Archmagus Selwyn Vayle", alignment: "NE", cr: "9", ac: 15, hitDice: [20, 8], str: 8, dex: 14, con: 12, int: 20, wis: 13, cha: 12,
    skills: "Arcana +11, History +9", saves: "INT +11, WIS +7",
    actions: [{ weapon: "Force Bolt", dice: "4d6", dmgType: "force", ability: "int", extra: "Ranged spell attack, range 120 ft." },
      { name: "Counterspell (via the Vayle Codex)", text: "As a reaction, Selwyn can attempt to counter a spell being cast within 60 ft., automatically succeeding against a spell of 3rd level or lower." }],
    desc: "Court Mage of the Ashcrown Empire. Bound to the Crown by an oath he's spent a decade quietly trying to undo." },
  { name: "General Thessaly Korrin", alignment: "LE", cr: "10", ac: 17, hitDice: [15, 10], str: 18, dex: 12, con: 16, int: 13, wis: 14, cha: 13,
    skills: "Athletics +8, Intimidation +5", saves: "STR +8, CON +7",
    actions: [{ weapon: "Korrin's Reckoning", dice: "2d6", dmgType: "bludgeoning", ability: "str" },
      { name: "Merciless Advance", text: "Once per turn, if Thessaly moves at least 10 ft. straight toward a creature before attacking it, that attack deals an extra 7 (2d6) damage." }],
    desc: "Field general known as \"the Ashcrown's Hammer.\" Put down the Cinder Coast rebellion two decades ago and has never quite outrun it." },
  { name: "Renn Ashwick", alignment: "N", cr: "6", ac: 16, hitDice: [15, 8], str: 10, dex: 18, con: 12, int: 16, wis: 15, cha: 14,
    skills: "Stealth +8, Deception +6, Insight +6", saves: "DEX +8, INT +7",
    actions: [{ weapon: "Ashwick's Needle", dice: "1d4", dmgType: "piercing", ability: "dex", extra: "Finesse, thrown (range 20/60). +2d6 poison damage against a creature that hasn't acted yet this combat." },
      { name: "Vanish (Recharge 5-6)", text: "Renn becomes invisible until the end of their next turn or until they attack." }],
    desc: "Spymaster of the Ashcrown Empire. Loyal to information first, the Crown second." },
  { name: "Firewarden Cassia Emberlyn", alignment: "LE", cr: "4", ac: 15, hitDice: [13, 8], str: 15, dex: 12, con: 16, int: 11, wis: 13, cha: 12,
    skills: "Intimidation +4, Insight +3", saves: "STR +4, CON +5",
    actions: [{ weapon: "Fire-Brand Cudgel", dice: "1d8", dmgType: "bludgeoning", ability: "str", extra: "Deals an extra 7 (2d6) fire damage." }],
    desc: "Firewarden for the Ashbond, Karvossa district. The true, hidden leader of its inner circle." },
  { name: "Auditor Voss Ferrand", alignment: "LE", cr: "2", ac: 13, hitDice: [13, 8], str: 9, dex: 12, con: 12, int: 15, wis: 13, cha: 17,
    skills: "Deception +6, Persuasion +6, Insight +4", saves: "CHA +6, WIS +4",
    actions: [{ name: "Called Debt", text: "As an action, Voss can 'call in' a debt held over one creature within 30 ft. that owes the Black Books: DC 15 Charisma save or that creature is Frightened of Voss for 1 minute." }],
    desc: "Regional debt-caller for the Black Books. Has never once needed to raise a hand." },
  { name: "Grand Inquisitor Darrow Vane", alignment: "LE", cr: "8", ac: 16, hitDice: [14, 8], str: 16, dex: 12, con: 17, int: 13, wis: 16, cha: 14,
    skills: "Insight +7, Intimidation +6, Religion +5, Persuasion +6", saves: "WIS +7, CON +7",
    actions: [{ weapon: "Vane's Judgment", dice: "1d6", dmgType: "bludgeoning", ability: "str", extra: "+2d6 radiant damage against a creature that has lied to Darrow in the last minute." },
      { name: "Detect Falsehood (At Will)", text: "Darrow can tell, with unsettling reliability, whether the last thing a creature said to him was a lie — though not what the truth actually is." },
      { name: "The Legion Seal", text: "As an action, Darrow can invoke a standing ordinance against one creature within 30 ft. who is a citizen of the Empire: DC 16 Wisdom save or the target is bound by a compulsory oath of his choosing for 24 hours (GM adjudicates specifics)." }],
    desc: "Grand Inquisitor and architect of the Queen's Legion. Would describe himself as a man who's never punished the innocent, and believes it." },
  { name: "Crown Prince Aldric Draventh", alignment: "NG", cr: "3", ac: 14, hitDice: [12, 8], str: 12, dex: 14, con: 14, int: 13, wis: 12, cha: 16,
    skills: "Persuasion +5, Deception +5", saves: "DEX +4, CHA +5",
    actions: [{ weapon: "Courtly Rapier", dice: "1d8", dmgType: "piercing", ability: "dex" }],
    desc: "Heir to the Ashcrown throne. Has spent his whole adult life performing exactly the heir his mother expects." },

  // ── Neutral ──
  { name: "Mirna Thatch", alignment: "LN", cr: "1/8", ac: 11, hitDice: [5, 8], str: 12, dex: 11, con: 13, int: 11, wis: 13, cha: 13,
    skills: "Insight +3, Persuasion +2",
    actions: [{ weapon: "Iron Skillet", dice: "1d6", dmgType: "bludgeoning", ability: "str" }],
    desc: "Proprietor of the Guttering Lantern. Makes exactly one rule stick, and it always sticks." },
  { name: "Toren Iresmith", alignment: "N", cr: "1/2", ac: 13, hitDice: [6, 8], str: 15, dex: 11, con: 14, int: 11, wis: 11, cha: 10,
    skills: "",
    actions: [{ weapon: "Smithing Hammer", dice: "1d8", dmgType: "bludgeoning", ability: "str" }],
    desc: "Independent smith. Quietly overcharges Concord officials and undercharges everyone else." },
  { name: "\"Whisper\"", alignment: "CN", cr: "1", ac: 14, hitDice: [7, 8], str: 9, dex: 16, con: 13, int: 15, wis: 14, cha: 13,
    skills: "Stealth +6, Deception +4, Insight +4",
    actions: [{ weapon: "Concealed Dagger", dice: "1d4", dmgType: "piercing", ability: "dex" }],
    desc: "Information broker. Nobody in Karvossa knows the real name or face — including, allegedly, most clients." },
  { name: "Kade Ostergaard", alignment: "CN", cr: "5", ac: 16, hitDice: [11, 8], str: 18, dex: 13, con: 18, int: 11, wis: 12, cha: 14,
    skills: "Athletics +6, Intimidation +4",
    actions: [{ weapon: "Longsword", dice: "1d8", dmgType: "slashing", ability: "str" },
      { name: "Rally", text: "Once per short rest, Kade can grant up to 4 allies within 30 ft. 10 temporary hit points as a bonus action." }],
    desc: "Captain of the Ashen Blades mercenary company. Picky about politics, professional about everything else." },
  { name: "Dr. Aveline Correll", alignment: "NG", cr: "1/8", ac: 11, hitDice: [4, 8], str: 8, dex: 12, con: 12, int: 15, wis: 15, cha: 13,
    skills: "Medicine +4, Insight +4",
    actions: [{ weapon: "Surgical Knife", dice: "1d4", dmgType: "piercing", ability: "dex" }],
    desc: "Physician who treats whoever walks through her door, Imperial or rebel, and has made it a point of principle." },
  { name: "\"Baron\" Ezra Coldwell", alignment: "LN", cr: "0", ac: 10, hitDice: [4, 8], str: 9, dex: 10, con: 10, int: 13, wis: 12, cha: 13,
    skills: "Persuasion +3",
    actions: [{ weapon: "Walking Cane", dice: "1d4", dmgType: "bludgeoning", ability: "str" }],
    desc: "Self-styled merchant guildmaster. Not actually a baron; almost everyone's forgotten that by now." },
  { name: "Old Yura", alignment: "CN", cr: "1", ac: 12, hitDice: [7, 8], str: 8, dex: 12, con: 11, int: 14, wis: 17, cha: 15,
    skills: "Insight +6, Deception +5",
    actions: [{ name: "Minor Hex", text: "Ranged Spell Attack: +5 to hit, range 30 ft. Hit: 7 (2d6) necrotic damage." }],
    desc: "Fortune teller with an unsettlingly good cold reading. Secretly the Cinderwright, the Second Flame's most effective propagandist." },
  { name: "Finn Callaway", alignment: "CN", cr: "1/2", ac: 13, hitDice: [6, 8], str: 14, dex: 14, con: 13, int: 10, wis: 12, cha: 11,
    skills: "Athletics +4, Perception +3",
    actions: [{ weapon: "Boat Hook", dice: "1d6", dmgType: "piercing", ability: "str" }],
    desc: "Dockhand who moves whatever pays, with one quiet, hard-won exception." },
  { name: "Sergeant Hollis Brake", alignment: "LN", cr: "2", ac: 15, hitDice: [9, 8], str: 15, dex: 13, con: 15, int: 11, wis: 13, cha: 11,
    skills: "Athletics +4, Perception +3",
    actions: [{ weapon: "Old Service Sword", dice: "1d8", dmgType: "slashing", ability: "str" }],
    desc: "Retired Imperial soldier, honorably discharged, running a training yard on the edge of Karvossa." },
  { name: "Lysette Vane", alignment: "CG", cr: "1/2", ac: 12, hitDice: [6, 8], str: 10, dex: 14, con: 11, int: 12, wis: 13, cha: 16,
    skills: "Performance +5, Persuasion +5",
    actions: [{ weapon: "Rapier", dice: "1d8", dmgType: "piercing", ability: "dex" }],
    desc: "Traveling entertainer whose songs sound apolitical right up until a listener actually thinks about the lyrics." },

  // ── Rebel ──
  { name: "Commander Elara Thorne", alignment: "CG", cr: "8", ac: 16, hitDice: [14, 8], str: 18, dex: 14, con: 18, int: 12, wis: 14, cha: 16,
    skills: "Athletics +7, Intimidation +6, Insight +5", saves: "STR +7, CON +7",
    actions: [{ weapon: "Thorne's Answer", dice: "1d8", dmgType: "slashing", ability: "str", extra: "+2d6 more against a creature wearing Ashcrown colors that Elara has hit within the last minute." },
      { name: "Unbreakable Line (1/Day)", text: "Elara and up to 5 allies within 30 ft. gain advantage on saving throws against being Frightened for 1 hour." }],
    desc: "Leader of the Second Flame. Deserted the Ashcrown army nine years ago and has never once explained the order that broke her." },
  { name: "Garrick Sable", alignment: "NG", cr: "5", ac: 16, hitDice: [10, 8], str: 17, dex: 13, con: 18, int: 12, wis: 13, cha: 12,
    skills: "Athletics +5, Persuasion +3",
    actions: [{ weapon: "Imperial-Issue Longsword", dice: "1d8", dmgType: "slashing", ability: "str" }],
    desc: "Former Imperial officer, defected under Lord Commander Reave. Trains the Second Flame's newest recruits." },
  { name: "\"Nyx\"", alignment: "CN", cr: "4", ac: 15, hitDice: [12, 8], str: 11, dex: 17, con: 13, int: 14, wis: 13, cha: 12,
    skills: "Stealth +6, Sleight of Hand +6",
    actions: [{ weapon: "Throwing Knives", dice: "1d4", dmgType: "piercing", ability: "dex", extra: "Thrown (range 20/60)." }],
    desc: "Saboteur. Nobody in the Second Flame, including Commander Thorne, knows their real name." },
  { name: "Captain Rhoswen Ash", alignment: "CG", cr: "4", ac: 15, hitDice: [12, 8], str: 15, dex: 14, con: 14, int: 11, wis: 13, cha: 14,
    skills: "Athletics +4, Intimidation +4",
    actions: [{ weapon: "Cinder Coast Spear", dice: "1d6", dmgType: "piercing", ability: "str", extra: "Reach 10 ft. +1d6 fire damage." }],
    desc: "Field commander leading the Second Flame's northern companies. Carries an inherited grudge with a specific name on it." },
  { name: "Ophir Lund", alignment: "CG", cr: "3", ac: 13, hitDice: [10, 8], str: 9, dex: 14, con: 13, int: 17, wis: 12, cha: 11,
    skills: "Arcana +5, Investigation +5",
    actions: [{ name: "Scorching Ray", text: "Ranged Spell Attack: +5 to hit, range 60 ft. Hit: 10 (3d6) fire damage." }],
    desc: "Rebel battle-mage, washed out of the Ashcrown academy for refusing the Crown's binding oath." },
  { name: "\"Big\" Tam Wexley", alignment: "NG", cr: "2", ac: 14, hitDice: [8, 8], str: 16, dex: 11, con: 16, int: 12, wis: 13, cha: 13,
    skills: "Athletics +5, Persuasion +3",
    actions: [{ weapon: "Loading Hook", dice: "1d8", dmgType: "piercing", ability: "str" }],
    desc: "Quartermaster. Has fed, armed, and equipped more of the rebellion than anyone realizes." },
  { name: "Wren Ashby", alignment: "CG", cr: "1/4", ac: 12, hitDice: [4, 8], str: 11, dex: 14, con: 11, int: 10, wis: 11, cha: 12,
    skills: "Athletics +2",
    actions: [{ weapon: "Hand Axe", dice: "1d6", dmgType: "slashing", ability: "str", extra: "Thrown (range 20/60)." }],
    desc: "New recruit, seventeen, furious about a conscripted cousin, still learning how slow real resistance actually is." },
  { name: "\"Old Marrow\"", alignment: "CN", cr: "5", ac: 14, hitDice: [11, 8], str: 17, dex: 12, con: 15, int: 11, wis: 13, cha: 12,
    skills: "Athletics +6, Survival +4",
    actions: [{ weapon: "Notched Battleaxe", dice: "1d8", dmgType: "slashing", ability: "str" }],
    desc: "Veteran of every major Second Flame engagement since its founding. Even they aren't sure anymore what their real name was." },
];

// ===================== NPC CONNECTIONS =====================
// Backing data for the DM Controls "Web" sub-tab (see renderNpcWebTab in the main file) — a
// quick-reference allegiance/relationship chart, distinct from NPC_LIBRARY itself. Keyed by
// NPC_LIBRARY id rather than duplicating name/faction/title (those are read live from
// NPC_LIBRARY at render time, npcEdits overlay included, so an edited NPC's name/faction still
// shows correctly here without this file needing to change).
//
// One shape:
//   {
//     id: "matches an NPC_LIBRARY id",
//     allegiance: "a short phrase — who they ACTUALLY serve, which may differ from faction",
//     connections: ["short phrases, one per notable tie to another NPC, org, or plot thread"],
//   }
// Every entry in NPC_LIBRARY has an entry here, including "the-patron" -- the Web tab is meant
// to be a complete map of the cast, not just the twists. Entries with nothing hidden still get
// a short, honest allegiance line rather than being left out.
const NPC_CONNECTIONS = [
  { id: "empress-isolde", allegiance: "The Crown, in her own mind — in truth, unknowingly serving the oligarch cabal that controls her",
    connections: ["Secretly manipulated by Grand Inquisitor Darrow Vane (the rite) and Auditor Voss Ferrand (the tinctures)", "Mother of Crown Prince Aldric Draventh, who funds the rebellion against her without knowing she's a victim too"] },
  { id: "lord-commander-reave", allegiance: "Nominally the Crown — genuinely, only his sister",
    connections: ["Protects his sister Sela (not a full NPC entry), whose care depends on his continued Imperial service", "Rival in raw power to General Thessaly Korrin", "Former commanding officer of Second Flame defector Garrick Sable"] },
  { id: "archmagus-vayle", allegiance: "The Crown, out of obligation rather than belief",
    connections: ["Secretly the intelligence conduit for Ophir Lund's espionage — may not fully realize what he's actually relaying", "Quietly working to break his own binding oath to the Crown"] },
  { id: "general-korrin", allegiance: "The Empire, genuinely — and separately, paid by the oligarch cabal",
    connections: ["Bought by the same oligarch cabal that manages the throne", "Unknowingly condemned Captain Rhoswen Ash's family two decades ago at the Cinder Coast", "Signed the official (false) execution record for \"Old Marrow\"", "Rival in raw power to Lord Commander Reave"] },
  { id: "spymaster-ashwick", allegiance: "Information itself, more than the Crown",
    connections: ["Already suspects Crown Prince Aldric is the Second Flame's Patron — hasn't reported it"] },
  { id: "firewarden-emberlyn", allegiance: "The Ashbond's hidden inner circle, which she secretly leads",
    connections: ["True leader of the Ashbond's 'Deepening' circle — founder Zaharos has no idea", "Her district quietly overlooks blacksmith Toren Iresmith's minor tax protest"] },
  { id: "auditor-ferrand", allegiance: "The oligarch cabal, via the Black Books",
    connections: ["Supplies Grand Inquisitor Vane with the tinctures used on Empress Isolde", "Doesn't know the First Creditor he answers to is a sentient book, not a person", "Quietly overlooks Guildmaster Coldwell's supply-contract skimming"] },
  { id: "grand-inquisitor-vane", allegiance: "The oligarch cabal, via the Queen's Legion he built and the rite he performs on the Empress",
    connections: ["Founder and architect of the Queen's Legion", "Personally administers Empress Isolde's 'loyalty devotions', in alliance with Auditor Ferrand", "One of only two people alive who know the Legion and the throne answer to the same cabal", "Estranged brother of entertainer Lysette Vane, has her secretly watched", "Has ordered all three Inquisitorial investigations into the Cinderwright — unknowingly investigating Old Yura"] },
  { id: "prince-aldric", allegiance: "Secretly the Second Flame, as its anonymous \"Patron\"",
    connections: ["Anonymous financier of the Second Flame", "Son of Empress Isolde — doesn't know she's a victim of manipulation, not just a willing tyrant", "Identity already suspected by Spymaster Ashwick"] },
  { id: "innkeeper-thatch", allegiance: "Neutral, genuinely — good business is good business",
    connections: ["Lets Second Flame couriers use her cellar as a dead drop"] },
  { id: "blacksmith-iresmith", allegiance: "Neutral, with a quiet private protest against the Ashbond",
    connections: ["Small ongoing tax protest against Ashbond licensing, quietly overlooked by Firewarden Emberlyn's own district"] },
  { id: "broker-whisper", allegiance: "No one — strictly transactional",
    connections: ["Moves Old Yura's Cinderwright pamphlets through the city", "Arranges Finn Callaway and \"Big\" Tam Wexley's smuggling handoffs", "Secretly three different people sharing one identity"] },
  { id: "mercenary-ostergaard", allegiance: "The Ashen Blades' own survival and reputation, above any faction",
    connections: ["Turned down a lucrative Reave-offered contract to occupy a rebel-sympathetic town"] },
  { id: "physician-correll", allegiance: "Neutral — treats anyone, picks no side",
    connections: ["Quietly suspects Crown Prince Aldric's recurring wound comes from rebel activity"] },
  { id: "guildmaster-coldwell", allegiance: "Neutral, profitably",
    connections: ["Skims Imperial military supply contracts — Auditor Ferrand quietly lets it slide"] },
  { id: "hedge-mage-yura", allegiance: "Secretly the Second Flame, as the Cinderwright",
    connections: ["Secretly the Cinderwright, the rebellion's most effective propagandist", "Her real, minor prophetic gift has personally stalled all three Inquisitorial investigations against her", "Moves her pamphlets through Whisper"] },
  { id: "smuggler-callaway", allegiance: "Neutral on paper — quietly aids the Second Flame",
    connections: ["Moves Second Flame supplies through the docks, arranged via Whisper", "Coordinates logistics with \"Big\" Tam Wexley"] },
  { id: "veteran-brake", allegiance: "Neutral publicly — quietly sympathetic to the Second Flame",
    connections: ["Secretly trains a handful of Second Flame recruits under cover of ordinary lessons"] },
  { id: "entertainer-lysette", allegiance: "Neutral, no politics by design",
    connections: ["Estranged younger sister of Grand Inquisitor Darrow Vane, unknowingly watched by him for years"] },
  { id: "commander-thorne", allegiance: "The Second Flame — leads it",
    connections: ["Doesn't know the Patron's true identity, suspects it traces back to the palace", "Commands Captain Rhoswen Ash and Spymaster \"Nyx\""] },
  { id: "defector-sable", allegiance: "The Second Flame, since defecting from Reave's command",
    connections: ["Former officer under Lord Commander Reave", "Maintains a secret dead-drop correspondence with a friend still serving under Reave", "Personally vouching for recruit Wren Ashby's advancement"] },
  { id: "saboteur-nyx", allegiance: "The Second Flame — true identity unknown even to Commander Thorne",
    connections: ["Reports to Elara Thorne through Garrick Sable", "Has shown Thorne undisclosed mercy toward Imperial patrols to protect civilians"] },
  { id: "field-commander-ash", allegiance: "The Second Flame, personally driven",
    connections: ["Carries a generational grudge against General Korrin over the Cinder Coast campaign", "Korrin has recently identified her as that family's daughter", "Commands mage Ophir Lund's company — unknowingly compromised by him"] },
  { id: "rebel-mage-lund", allegiance: "Secretly the Empire, via Archmagus Vayle",
    connections: ["Secretly feeds Empire intelligence on Rhoswen Ash's company through his old teacher, Selwyn Vayle", "Fights genuinely hard for the Second Flame despite his true loyalty"] },
  { id: "quartermaster-wexley", allegiance: "The Second Flame, entirely",
    connections: ["Coordinates supply runs with Finn Callaway, arranged via Whisper"] },
  { id: "recruit-ashby", allegiance: "The Second Flame, idealistically",
    connections: ["Being quietly vouched for by Garrick Sable for more dangerous assignments"] },
  { id: "veteran-old-marrow", allegiance: "The Second Flame, unwaveringly",
    connections: ["Officially listed as executed in Imperial records — under General Korrin's own old signature"] },
  { id: "the-patron", allegiance: "Secretly the Second Flame's own anonymous financier",
    connections: ["Actually Crown Prince Aldric Draventh", "Identity already suspected by Spymaster Ashwick"] },
];
